import {readFile,writeFile} from 'node:fs/promises';
import {regions,harmonize,calendar,inRegion} from './core.js';
import {readSnapshot} from './read-snapshot.js';
const s=await readSnapshot();
const lines=['# NASA observation analysis','',`Retrieved: ${s.retrievedAt}. Observation dates: ${s.dateStart} through ${s.dateEnd} (UTC).`,`Products: MODIS_NRT and VIIRS_NOAA20_NRT. ${s.data.length.toLocaleString()} raw thermal-anomaly observations worldwide.`, '', 'All figures below apply the dashboard default normalized confidence threshold of 40. VIIRS l/n/h maps heuristically to 30/70/95. Counts are observations and occupied grid cells, not unique fires or burned area.','','| Study area | Raw records before filter | MODIS selected | VIIRS selected | Daily occupied cells | Cells with both sensors |','|---|---:|---:|---:|---:|---:|'];
for(const region of Object.keys(regions)){const all=s.data.filter(r=>inRegion(r,region)),raw=all.filter(r=>r.confidence>=40),cells=harmonize(raw);lines.push(`| ${region} | ${all.length} | ${raw.filter(r=>r.sensor==='MODIS').length} | ${raw.filter(r=>r.sensor==='VIIRS').length} | ${cells.length} | ${cells.filter(r=>r.sensors.length>1).length} |`);}
lines.push('','## Daily burning activity','','| Area | UTC date | Daily occupied cells |','|---|---|---:|');
for(const region of Object.keys(regions)){const cells=harmonize(s.data.filter(r=>inRegion(r,region)&&r.confidence>=40));for(const d of calendar(cells,s.dateStart,s.dateEnd))lines.push(`| ${region} | ${d.date} | ${d.count} |`);}
lines.push('','These five days are insufficient to establish seasonal patterns or historical anomalies. Larger VIIRS counts do not by themselves show an increase in real burning: sensor sampling, sensitivity, cloud cover, and resolution differ. Cross-sensor occupied cells indicate spatial/date overlap under this approximate grid; they are not validated matches between fire events. Some thermal anomalies can be agricultural or industrial heat sources. Region filters use rectangular bounding boxes.','','Source: https://firms.modaps.eosdis.nasa.gov/api/area/');
await writeFile('NASA-DATA-ANALYSIS.md',lines.join('\n')+'\n');console.log(lines.slice(0,14).join('\n'));
