import {parseArea} from './area-bounds.js';
import {createAreaSelection} from './area-selection.js';
import {mapOptions,tileOptions,minimumWorldZoom} from './map-policy.js';
import {nextDateRange,feedHealth} from './refresh-state.js';
import {regions} from './core.js';
import {basemaps,imageryDate} from './basemaps.js';
import {createHotspotLayer} from './hotspot-layer.js';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),colors={MODIS:'#ff965c',VIIRS:'#77bfff',Harmonized:'#a5e6bc'};
const worker=new Worker(new URL('./analysis-worker.js',import.meta.url),{type:'module'});let rpcID=0;const pending=new Map();
function ask(type,args){return new Promise((resolve,reject)=>{const id=++rpcID;pending.set(id,{resolve,reject});worker.postMessage({id,type,args});});}
worker.onmessage=({data:{id,result,error}})=>{const p=pending.get(id);if(!p)return;pending.delete(id);error?p.reject(Error(error)):p.resolve(result);};
worker.onerror=()=>{for(const p of pending.values())p.reject(Error('Background processing unavailable'));pending.clear();$('status').textContent='Background data processing could not start. Try loading the page again.';};
let view=['Harmonized','MODIS','VIIRS','Compare'].includes(params.get('view'))?params.get('view'):'Harmonized',day=params.get('day')||null,snapshot=null,busy=false,lastCheck=null,failed=false,query=0,drawID=0,summary=null;
$('region').replaceChildren(...Object.keys(regions).map(name=>{const option=document.createElement('option');option.value=option.textContent=name;return option;}));$('region').value=regions[params.get('region')]?params.get('region'):'World';
$('confidence').value=Math.max(0,Math.min(100,Number(params.get('confidence')??40)));$('follow-latest').checked=params.get('follow')!=='0';
if(/^\d{4}-\d{2}-\d{2}$/.test(params.get('start')||''))$('start').value=params.get('start');if(/^\d{4}-\d{2}-\d{2}$/.test(params.get('end')||''))$('end').value=params.get('end');
const initialArea=parseArea(params.get('area'));if(initialArea)$('region').value='World';
const map=L.map('map',{...mapOptions,zoomAnimation:window.atlasMotion.enabled,fadeAnimation:window.atlasMotion.enabled}).setView(regions[$('region').value].center,3);
const areaSelection=createAreaSelection(map,{button:$('select-area'),clearButton:$('clear-area'),status:$('area-status'),initialBounds:initialArea,onChange(bounds){if(bounds)$('region').value='World';day=null;freshness();render();updateMapLink();}});
const hotspots=createHotspotLayer(map,inspect);let bases=[],base='satellite',baseKey='',savedView=false;
if(initialArea){map.fitBounds([[initialArea[1],initialArea[0]],[initialArea[3],initialArea[2]]],{animate:false,padding:[30,30]});savedView=true;}
const pointView=[params.get('lat'),params.get('lon'),params.get('zoom')].map(Number);if(params.has('lat')&&pointView.every(Number.isFinite)&&Math.abs(pointView[0])<85&&Math.abs(pointView[1])<=180&&pointView[2]>=0&&pointView[2]<=18){map.setView(pointView.slice(0,2),pointView[2]);savedView=true;}
let mapSize='';function sizeMap(){const element=$('map'),next=element.clientWidth+':'+element.clientHeight;if(next===mapSize)return;mapSize=next;map.invalidateSize({pan:false});map.setMinZoom(minimumWorldZoom(map.getSize()));draw();}new ResizeObserver(sizeMap).observe($('map'));
function viewport(){const origin=map.getPixelBounds().min,size=map.getSize();return {zoom:map.getZoom(),origin:{x:origin.x,y:origin.y},width:size.x,height:size.y,cellSize:(map.getZoom()<6?28:map.getZoom()<9?16:8)*(window.atlasMotion.enabled?1:1.5)};}
let drawing=null,drawRequested=false,visibleBins=[];
const accessible=document.querySelector('.map-accessible');
function updateVisibleList(){
 if(!accessible.open)return;
 const top=[];for(const bin of visibleBins){let i=top.findIndex(b=>b.count<bin.count);if(i<0)i=top.length;if(i<12){top.splice(i,0,bin);if(top.length>12)top.pop();}}
 $('visible-list').replaceChildren(...top.map(bin=>{const button=document.createElement('button');button.textContent=bin.sensor+': '+bin.count.toLocaleString()+' at '+bin.lat.toFixed(2)+'\u00b0, '+bin.lon.toFixed(2)+'\u00b0';button.onclick=()=>inspect(bin);return button;}));
}
accessible.addEventListener('toggle',updateVisibleList);
// Never queue obsolete viewport jobs behind a drag or a filter change.
function draw(){
 if(!snapshot||!summary)return Promise.resolve();
 drawRequested=true;++drawID;if(drawing)return drawing;
 drawing=(async()=>{
  while(drawRequested){
   drawRequested=false;const id=drawID,args=viewport();
   try{const result=await ask('points',args),current=viewport();if(id!==drawID||args.zoom!==current.zoom||args.origin.x!==current.origin.x||args.origin.y!==current.origin.y||args.width!==current.width||args.height!==current.height)continue;
    hotspots.paint(result.bins);visibleBins=result.bins;updateVisibleList();
    $('map-density').textContent=result.visible.toLocaleString()+' selected detections \u00b7 '+result.bins.length.toLocaleString()+' map symbols \u00b7 zoom in for detail';
   }catch{$('map-density').textContent='Map update unavailable; check the data connection.';}
  }
 })().finally(()=>{drawing=null;});
 return drawing;
}
map.on('moveend',()=>{draw();updateMapLink();});
function inspect(bin){if(areaSelection.active)return;const el=document.createElement('div'),title=document.createElement('strong');title.textContent=bin.count>1?`${bin.count.toLocaleString()} ${bin.sensor} detections in this map symbol`:bin.sample.sensor+' detection';el.append(title);const row=bin.sample;
 const lines=bin.count>1?[`${bin.observations.toLocaleString()} underlying observations. Map grouping is for display only.`,`Selected view: ${view}. Zoom in to separate nearby detections.`]:[`${row.date} ${row.time} UTC`,`${row.lat.toFixed(4)}, ${row.lon.toFixed(4)}`,`Confidence: ${row.confidence}% · ${row.frp===null?'FRP unavailable':row.frp+' MW FRP'}`,row.sensors?`Sensors: ${row.sensors.join(' + ')} · ${row.observations} observations · ${row.timeStart}–${row.timeEnd} UTC`:`Satellite: ${row.satellite} · ${row.product} · original confidence: ${row.confidenceRaw}`];
 for(const line of lines){const p=document.createElement('p');p.textContent=line;el.append(p);}if(bin.count>1){const button=document.createElement('button');button.textContent='Zoom to these detections';button.onclick=()=>{const [s,w,n,e]=bin.bounds;map.closePopup();map.fitBounds([[s,w],[n,e]],{maxZoom:Math.min(18,map.getZoom()+3),padding:[35,35],animate:window.atlasMotion.enabled});};el.append(button);}
 L.popup({className:'atlas-popup',maxWidth:320}).setLatLng([bin.lat,bin.lon]).setContent(el).openOn(map);
}
function filters(){return {region:$('region').value,start:$('start').value,end:$('end').value,confidence:Number($('confidence').value),view,day,area:areaSelection.bounds};}
async function render(){if(!snapshot)return;const args=filters();if(!args.start||!args.end||args.start>args.end){$('status').textContent='Choose a valid UTC date range.';return;}const id=++query;++drawID;$('export').disabled=true;$('confidence-value').textContent=args.confidence+'%';$('map-density').textContent='Processing the selected NASA observations…';try{const result=await ask('analyze',args);if(id!==query)return;summary=result;areaSelection.setCount(result.selected);
 const metrics=[['Raw observations',result.raw,'Across both sensors'],['Daily occupied cells',result.cells,'Approximate 1 km grid'],['Multi-sensor cells',result.overlap,'Observed by MODIS + VIIRS'],['Critical days',result.days.filter(d=>d.critical).length,'Window-relative activity peaks']];$('metrics').innerHTML=metrics.map(([label,n,hint])=>`<div class="metric"><span>${label}</span><strong>${n.toLocaleString()}</strong><small>${hint}</small></div>`).join('');
 const max=Math.max(1,...result.days.map(d=>d.count));$('calendar').replaceChildren(...result.days.map(d=>{const b=document.createElement('button');b.className='day'+(d.critical?' critical':'')+(day===d.date?' picked':'');b.style.background=`rgba(165,230,188,${.06+.55*d.count/max})`;b.innerHTML=`<span>${d.date.slice(5)}</span><b>${d.count.toLocaleString()}</b>${d.critical?'<small>PEAK</small>':''}`;b.title=d.date+': '+d.count+' occupied cells';b.onclick=()=>{day=day===d.date?null:d.date;render();setBasemap(base);};return b;}));$('calendar-note').textContent=`${result.selected.toLocaleString()} selected detections${day?' on '+day:''}. Display clusters combine nearby symbols; exports retain every selected record. Peaks are relative to this date window, and the latest UTC day may be incomplete.`;
 const maxBar=Math.max(1,...result.bars.map(b=>b[1]));$('comparison').innerHTML=result.bars.map(([name,count])=>`<div class="bar-label"><span>${name}</span><b>${count.toLocaleString()}</b></div><div class="bar-track"><div style="width:${count/maxBar*100}%;background:${colors[name]}"></div></div>`).join('');updateMapLink();await draw();
 }catch{$('status').textContent='Analysis failed. Your last actual NASA observations remain available.';}finally{if(id===query)$('export').disabled=false;}}
function freshness(){if(!snapshot)return;const health=feedHealth(snapshot.retrievedAt);$('freshness').textContent='Retrieved '+health.ageLabel+' · worldwide NASA near-real-time';$('feed-state').textContent=failed?'Update unavailable':health.stale?'Data is stale':'Auto-updating';document.querySelector('.feed-bar').classList.toggle('stale',health.stale);document.querySelector('.feed-bar').classList.toggle('failed',failed);if($('map-filter-summary'))$('map-filter-summary').textContent=`Filters · ${areaSelection.bounds?'Selected area':$('region').value} · ${snapshot.dateStart}–${snapshot.dateEnd} UTC · ${$('feed-state').textContent}`;$('last-check').textContent=lastCheck?'Last checked '+lastCheck.toLocaleTimeString()+' · checks every 60s':'Checks every 60s';}
async function load(auto=false){if(busy)return;busy=true;try{
 if(auto&&snapshot){const version=await ask('version');if(version.retrievedAt===snapshot.retrievedAt){lastCheck=new Date();failed=false;freshness();return;}}
 if(!auto)$('status').textContent='Loading worldwide NASA observations in the background…';const result=await ask('load');const range=nextDateRange({start:$('start').value,end:$('end').value},result,$('follow-latest').checked);snapshot=result;lastCheck=new Date();failed=false;$('start').value=range.start;$('end').value=range.end;$('start').min=$('end').min=result.dateStart;$('start').max=$('end').max=result.dateEnd;if(day&&(day<range.start||day>range.end))day=null;$('status').textContent=result.message;freshness();if(!auto&&!savedView)fitRegion();setBasemap(base);await render();
 }catch{failed=true;lastCheck=new Date();$('status').textContent=snapshot?'Update failed. Keeping your last actual global NASA observations; retries continue.':'Global NASA observations are unavailable. Automatic retries continue; no synthetic records are substituted.';freshness();}finally{busy=false;}}
function fitRegion(){const b=regions[$('region').value].bounds;map.fitBounds([[Math.max(-80,b[1]),b[0]],[Math.min(80,b[3]),b[2]]],{animate:window.atlasMotion.enabled});}
function setBasemap(name){base=basemaps[name]?name:'satellite';const config=basemaps[base],date=imageryDate(snapshot?.dateEnd||new Date().toISOString().slice(0,10),day),nextKey=base+(base==='daily'?':'+date:'');$('basemap').value=base;$('imagery-note').textContent=config.note+(base==='daily'?' Imagery date: '+date+' UTC.':'');if(nextKey===baseKey){updateMapLink();return;}baseKey=nextKey;for(const layer of bases)map.removeLayer(layer);bases=[];map.getContainer().dataset.basemap=base;const specs=base==='daily'?[basemaps.satellite,config]:[config];for(const spec of specs){const layer=L.tileLayer(spec.url.replace('{date}',date),{...tileOptions,maxNativeZoom:spec.maxNativeZoom,attribution:spec.attribution}).addTo(map);bases.push(layer);layer.on('tileerror',()=>{$('imagery-note').textContent=config.note+' Some imagery tiles are unavailable; observations remain independent of the basemap.';});} $('basemap').value=base;$('imagery-note').textContent=config.note+(base==='daily'?' Imagery date: '+date+' UTC.':'');try{localStorage.setItem('atlas-basemap',base);}catch{}updateMapLink();}
$('basemap').replaceChildren(...Object.entries(basemaps).map(([value,config])=>{const option=document.createElement('option');option.value=value;option.textContent=config.label;return option;}));try{base=params.get('basemap')||localStorage.getItem('atlas-basemap')||base;}catch{}setBasemap(base);$('basemap').onchange=()=>setBasemap($('basemap').value);
function updateMapLink(){const link=$('map-page-link');if(!link)return;const url=new URL(link.href),f=filters(),center=map.getCenter();for(const [key,value] of Object.entries({...f,follow:$('follow-latest').checked?'1':'0',basemap:base,lat:center.lat.toFixed(5),lon:center.lng.toFixed(5),zoom:map.getZoom()})){if(value===null)url.searchParams.delete(key);else url.searchParams.set(key,String(value));}link.href=url.href;}
let filterTimer;for(const id of ['start','end','confidence'])$(id).addEventListener('input',()=>{day=null;$('export').disabled=true;if(id!=='confidence')$('follow-latest').checked=false;$('confidence-value').textContent=$('confidence').value+'%';clearTimeout(filterTimer);filterTimer=setTimeout(render,180);});$('region').onchange=()=>{areaSelection.clear({notify:false});day=null;fitRegion();render();freshness();};document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('selected',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});render();};});$('reset').onclick=()=>{day=null;render();setBasemap(base);};$('check-now').onclick=()=>load(true);$('follow-latest').onchange=()=>{if(snapshot&&$('follow-latest').checked){$('start').value=snapshot.dateStart;$('end').value=snapshot.dateEnd;day=null;render();}updateMapLink();};
$('export').onclick=async()=>{const button=$('export');button.disabled=true;button.textContent='Preparing export…';try{const csv=await ask('export');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));const a=document.createElement('a');a.href=url;a.download=`ember-atlas-${areaSelection.bounds?'selected-area':$('region').value.toLowerCase().replaceAll(' ','-')}-${view.toLowerCase()}.csv`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}finally{button.disabled=false;button.textContent='↓ Export observations';}};
const panel=document.querySelector('.map-panel'),parent=panel.parentNode,next=panel.nextSibling;let expanded=false;
function enlarge(){expanded=!expanded;if(expanded){document.body.append(panel);document.body.classList.add('map-expanded');panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');panel.setAttribute('aria-label','Expanded hotspot map');}else{parent.insertBefore(panel,next);document.body.classList.remove('map-expanded');panel.removeAttribute('role');panel.removeAttribute('aria-modal');}const button=$('enlarge-map');button.textContent=expanded?'↙ Close large map':'↗ Enlarge map';button.setAttribute('aria-expanded',String(expanded));button.focus();requestAnimationFrame(sizeMap);}
$('enlarge-map').onclick=enlarge;$('world-view').onclick=()=>{areaSelection.clear({notify:false});$('region').value='World';day=null;fitRegion();render();freshness();};
document.addEventListener('keydown',e=>{if(!expanded)return;if(e.key==='Escape'){e.preventDefault();enlarge();}if(e.key==='Tab'){const focusable=[...panel.querySelectorAll('button,select,a[href],input,[tabindex]:not([tabindex="-1"])')].filter(el=>el.offsetParent!==null),first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('atlas-motion-change',draw);setInterval(()=>{if(!document.hidden)load(true);},60000);setInterval(freshness,10000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)load(true);});sizeMap();load();
