import test from 'node:test';import assert from 'node:assert/strict';
import {evidenceGrid,footprintWeights,compatible,matchSensors,confidenceClass} from './harmonization.js';
import {fitSeasonalCalibration} from './seasonal-calibration.js';
const row={id:'m',sensor:'MODIS',product:'MODIS_SP',satellite:'Aqua',date:'2020-08-01',time:'13:00',lat:40,lon:65,scan:1,track:1,confidence:80,confidenceRaw:'80',frp:20,daynight:'D'};
test('footprint allocation conserves each observation, preserves source, and does not move with detection density',()=>{for(const lat of [-60,0,40,80,89]){const r={...row,lat};assert.ok(Math.abs(footprintWeights(r).reduce((s,c)=>s+c.weight,0)-1)<1e-10);}const cells=evidenceGrid([row,{...row,id:'repeat'}]);assert.ok(Math.abs(cells.reduce((s,c)=>s+c.evidenceWeight,0)-1)<1e-10);assert.ok(cells.every(c=>c.derived&&c.sourceObservationIDs.includes('MODIS_SP:m')&&c.uncertainty.calibratedProbability===null));assert.deepEqual(cells.map(c=>[c.lat,c.lon]),evidenceGrid([{...row,frp:100}]).map(c=>[c.lat,c.lon]));});
test('matching requires space, time, daynight; many VIIRS pixels can associate with one MODIS pixel',()=>{const v={...row,id:'v',sensor:'VIIRS',satellite:'N',scan:.375,track:.375,time:'13:10',confidenceRaw:'n'};assert.equal(compatible(row,v),true);assert.equal(compatible(row,{...v,time:'14:00'}),false);assert.equal(compatible(row,{...v,lon:66}),false);assert.equal(compatible(row,{...v,daynight:'N'}),false);assert.equal(compatible({...row,time:undefined},v),false);const m=matchSensors([row,v,{...v,lon:65.001,id:'v2'}]);assert.equal(m.matchedModis,1);assert.equal(m.matchedViirs,2);});
test('UTC midnight and longitude wrap are handled',()=>{assert.equal(compatible({...row,date:'2020-08-01',time:'23:55',lon:179.999},{...row,date:'2020-08-02',time:'00:05',lon:-179.999}),true);});
test('native confidence semantics and zero/invalid FRP are retained without fabricated probabilities',()=>{assert.equal(confidenceClass({...row,sensor:'VIIRS',confidenceRaw:'h'}),'high');assert.equal(confidenceClass({...row,confidence:40}),'nominal');assert.equal(evidenceGrid([{...row,frp:0}])[0].frp,null);assert.equal(evidenceGrid([{...row,frp:-1}])[0].frp,null);});
test('calibration never learns holdout or NRT and responds to season',()=>{const days=[];for(let y=2018;y<=2022;y++)for(const month of ['01','08'])for(let d=1;d<=20;d++)days.push({date:`${y}-${month}-${String(d).padStart(2,'0')}`,m:10,s:month==='01'?20:40,j:null,n:null,processing:'SP'});const a=fitSeasonalCalibration(days);const b=fitSeasonalCalibration(days.map(d=>+d.date.slice(0,4)>2020?{...d,m:9999}:d));assert.equal(a.months.s['01'].factor,b.months.s['01'].factor);assert.ok(a.months.s['01'].factor>a.months.s['08'].factor);assert.equal(fitSeasonalCalibration([]).factors.s.factor,null);});

test('daily co-occurrence is distinguished from near-time support',()=>{const v={...row,id:'v',sensor:'VIIRS',product:'VIIRS_SNPP_SP',scan:.375,track:.375};assert.ok(evidenceGrid([row,v]).some(c=>c.crossSensorCoincident));assert.ok(evidenceGrid([row,{...v,time:'18:00'}]).every(c=>!c.crossSensorCoincident));const c=evidenceGrid([row,{...v,id:'m'}]);assert.equal(new Set(c.flatMap(c=>c.sourceObservationIDs)).size,2);});
