import {createMapShell} from './map-shell.js';import {createAreaSelection} from './area-selection.js';import {createBoundaryExplorer} from './boundary-explorer.js';import {createHotspotLayer} from './hotspot-layer.js';
import {parseArea} from './area-bounds.js';
import {mapOptions,tileOptions,minimumWorldZoom} from './map-policy.js';import {basemaps,imageryDate} from './basemaps.js';
const $=id=>document.getElementById(id),params=new URLSearchParams(location.search),shell=createMapShell(document.querySelector('.map-panel'),{keepOutside:[document.querySelector('.history-calendar-card')]});
const worker=new Worker(new URL('./history-worker.js',import.meta.url),{type:'module'}),pending=new Map();let rpc=0;
function ask(type,args){return new Promise((resolve,reject)=>{const id=++rpc;pending.set(id,{resolve,reject});worker.postMessage({id,type,args});});}
worker.onmessage=({data})=>{const p=pending.get(data.id);if(!p)return;pending.delete(data.id);data.error?p.reject(Error(data.error)):p.resolve(data.result);};
worker.onerror=()=>{for(const p of pending.values())p.reject(Error('Historical processing could not start'));pending.clear();$('status').textContent='Historical processing unavailable. Live NASA observations remain available.';};
let metadata=null,result=null,caseID=params.get('case')||'uzbekistan',month=params.get('month'),view=['MODIS','VIIRS','Compare'].includes(params.get('view'))?params.get('view'):'Harmonized',boundary=null,query=0,selection=0,drawID=0,visible=true,bases=[],baseTicket=0,expanded=false,vectorAttribution=null;
try{visible=(params.get('detections')??localStorage.getItem('atlas-detections'))!=='0';}catch{}
const map=L.map('map',{...mapOptions,zoomAnimation:window.atlasMotion.enabled,fadeAnimation:window.atlasMotion.enabled}).setView([41,65],5);map.zoomControl.setPosition('bottomright');
const area=createAreaSelection(map,{button:$('select-area'),clearButton:$('clear-area'),status:$('area-status'),initialBounds:parseArea(params.get('area')),onChange(){boundaries.clear({notify:false});boundary=null;analyze();}});
const boundaries=createBoundaryExplorer(map,{isDrawing:()=>area.active,getPadding:()=>({padding:[30,50]}),onNotice:(name,o)=>shell.showSelection(name,o),onClear(){boundary=null;analyze();},onSelect(f){boundary=f;area.clear({notify:false});return analyze();}});
const hotspots=createHotspotLayer(map,inspect);
function visibility(){hotspots.setVisible(visible);++drawID;$('detections-toggle').textContent=visible?'Hide detections':'Show detections';$('detections-toggle').setAttribute('aria-pressed',String(!visible));document.querySelector('.map-panel').classList.toggle('detections-hidden',!visible);document.querySelector('.map-accessible').hidden=!visible;if(!visible){map.closePopup();$('visible-list').replaceChildren();}if(!visible)$('map-density').textContent='Detections hidden · Map navigation remains active';}
$('detections-toggle').onclick=()=>{visible=!visible;visibility();try{localStorage.setItem('atlas-detections',visible?'1':'0');}catch{}draw();};visibility();
document.querySelector('.explorer-topbar .mini-label').textContent='NASA FIRMS / HISTORICAL CELLS';document.querySelector('.explorer-topbar h2').textContent='Historical explorer';
function viewport(){const size=map.getSize(),origin=map.getPixelBounds().min;return {zoom:map.getZoom(),origin:{x:origin.x,y:origin.y},width:size.x,height:size.y,cellSize:map.getZoom()<6?28:map.getZoom()<9?16:8};}
let queued=false,running=false;
async function draw(){
 if(!result||!visible)return;queued=true;++drawID;if(running)return;running=true;
 try{while(queued&&visible){queued=false;const id=drawID,v=viewport(),r=await ask('points',v);if(id!==drawID||!visible)continue;hotspots.paint(r.bins);$('map-density').textContent=r.visible.toLocaleString()+' cell symbols · '+month+' · source counts retained';const list=$('visible-list');list.replaceChildren(...r.bins.slice(0,12).map(b=>{const button=document.createElement('button');button.textContent=b.sensor+' · '+b.observations+' source observations';button.onclick=()=>inspect(b);return button;}));}}
 catch{$('status').textContent='Map update unavailable. Last loaded historical analysis remains visible.';}finally{running=false;}
}
map.on('moveend',draw);function resize(){map.invalidateSize({pan:true,animate:false,debounceMoveend:true});map.setMinZoom(minimumWorldZoom(map.getSize()));draw();}
new ResizeObserver(resize).observe($('map'));$('map').addEventListener('atlas-map-layout',resize);
function inspect(bin){
 if(!visible||area.active)return;const r=bin.sample,box=document.createElement('div'),h=document.createElement('strong');h.textContent=bin.sensor+' · '+bin.count+' daily cells';box.append(h);
 for(const value of [r.date+' · '+r.timeStart+'–'+r.timeEnd+' UTC','MODIS: '+r.m+' · S-NPP: '+r.s+' · NOAA-20: '+r.j+' · NOAA-21: '+r.n,bin.observations+' quality-filtered source observations','Products: '+r.products.join(', '),'Maximum FRP: '+(r.frp===null?'unavailable':r.frp+' MW'),'Historical cells use grid centers, not original point coordinates.']){const p=document.createElement('p');p.textContent=value;box.append(p);}
 L.popup({className:'atlas-popup',maxWidth:330}).setLatLng([bin.lat,bin.lon]).setContent(box).openOn(map);
}
async function setBasemap(name){
 if(vectorAttribution){map.attributionControl.removeAttribution(vectorAttribution);vectorAttribution=null;}const ticket=++baseTicket,config=basemaps[name]||basemaps.satellite,date=[month?month+'-15':'2024-08-15',new Date().toISOString().slice(0,10)].sort()[0];for(const layer of bases)map.removeLayer(layer);bases=[];map.getContainer().dataset.vectorReady='false';map.getContainer().dataset.basemap=name;map.getContainer().dataset.imageryDate=date;map.fire('basemapchange');$('imagery-note').textContent=config.note+(name==='daily'?' Imagery date: '+date+' UTC.':'');
 const specs=config.vector?[basemaps.satellite]:name==='daily'?[basemaps['blue-marble'],config]:[config];
 for(const spec of specs)bases.push(L.tileLayer(spec.url.replace('{date}',date),{...tileOptions,maxNativeZoom:spec.maxNativeZoom,attribution:spec.attribution}).addTo(map));
 if(config.vector)try{const {createVectorBasemap}=await import('./vector-basemap.js');const layer=await createVectorBasemap(name);if(ticket!==baseTicket)return;layer.addTo(map);for(const fallback of bases)map.removeLayer(fallback);bases=[layer];map.attributionControl.addAttribution(config.attribution);vectorAttribution=config.attribution;map.getContainer().dataset.vectorReady='true';map.fire('basemapchange');}catch{$('imagery-note').textContent='Street renderer unavailable; satellite background and English labels remain available.';}
}
$('basemap').replaceChildren(...Object.entries(basemaps).map(([name,c])=>{const o=document.createElement('option');o.value=name;o.textContent=c.label;return o;}));let initialBase=params.get('basemap');try{initialBase||=localStorage.getItem('atlas-basemap');}catch{}$('basemap').value=basemaps[initialBase]?initialBase:'satellite';$('basemap').onchange=()=>{try{localStorage.setItem('atlas-basemap',$('basemap').value);}catch{}setBasemap($('basemap').value);};setBasemap($('basemap').value);
function era(){const date=(month||'')+'-01';$('sensor-era').textContent=date<'2012-01-20'?'MODIS era; S-NPP begins 20 Jan 2012':date<'2018-04-01'?'MODIS + S-NPP overlap':'MODIS + S-NPP + NOAA-20 overlap; actual coverage varies by product';}

function renderCalendar(){
 const table=document.createElement('table'),caption=document.createElement('caption');caption.textContent='Monthly burning activity · MODIS-scale seasonal activity index. Missing source coverage is shown as a dash.';table.append(caption);
 const head=document.createElement('thead'),tr=document.createElement('tr');tr.innerHTML='<th scope="col">Year</th>'+['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'].map(m=>'<th scope="col">'+m+'</th>').join('');head.append(tr);table.append(head);const body=document.createElement('tbody');
 const max=Math.max(1,...result.months.map(m=>m.index)),byMonth=new Map(result.months.map(m=>[m.month,m]));
 for(let year=Number($('history-from').value);year<=Number($('history-to').value);year++){
  const row=document.createElement('tr'),label=document.createElement('th');label.scope='row';label.textContent=year;row.append(label);
  for(let m=1;m<=12;m++){const key=year+'-'+String(m).padStart(2,'0'),p=byMonth.get(key),td=document.createElement('td');
   if(!p){td.textContent='—';td.title='No historical source coverage';td.className='history-missing';}
   else{const b=document.createElement('button');b.type='button';b.dataset.month=key;b.className='heat-cell'+(month===key?' selected':'');b.style.setProperty('--heat',(.12+.8*Math.log1p(p.index)/Math.log1p(max)).toFixed(3));b.textContent=Math.round(p.index).toLocaleString();b.title=key+' · Index '+p.index.toFixed(1)+' · '+p.state+' · '+(p.percentile===null?'insufficient history':p.percentile.toFixed(0)+'th seasonal percentile')+' · MODIS '+p.modisRaw+' / VIIRS '+p.viirsRaw+' source detections · '+p.coveredDays+'/'+p.daysInMonth+' days'+(p.provisional?' · provisional NRT':'');b.setAttribute('aria-label',b.title);b.setAttribute('aria-pressed',String(month===key));b.onclick=()=>{month=key;select();};td.append(b);}row.append(td);
  }body.append(row);
 }table.append(body);$('history-calendar').replaceChildren(table);
}
function modelDescription(){
 const mm=(month||'').slice(5,7),factor=result.model.months?.s?.[mm]||result.model.factors.s,other=result.model.months?.j?.[mm]||result.model.factors.j;
 $('model-note').textContent='Seasonal regional activity model · trained through '+result.model.throughYear+'. MODIS-scale index = mean(MODIS occupied cells, normalized reference VIIRS cells) when both exist; otherwise use the available calibrated contribution. Reference VIIRS: S-NPP, with NOAA-20 fallback. '+(factor.factor===null?'S-NPP calibration unavailable.':'S-NPP factor '+factor.factor.toFixed(3)+' from '+factor.pairedDays+' month-stratum days; held-out '+(factor.days??factor.holdoutDays)+' days, RMSE '+(factor.rmse?.toFixed(1)??'unavailable')+' occupied cells/day.')+(other.factor===null?'':' NOAA-20 factor '+other.factor.toFixed(3)+'.')+' Month-specific ratios shrink toward regional factors; sparse months fall back. Stability ranges are not probabilities. This is not a validated fire-risk product.';
}
function metric(label,value,hint){const el=document.createElement('div');el.className='metric';const a=document.createElement('span'),b=document.createElement('strong'),c=document.createElement('small');a.textContent=label;b.textContent=value;c.textContent=hint;el.append(a,b,c);return el;}
async function select(){
 if(!result||!month)return;const id=++selection;++drawID;hotspots.paint([]);$('export').disabled=true;era();
 try{const r=await ask('select',{month,view});if(id!==selection||r.stale)return;const p=r.period;if(!p)return;
 $('metrics').replaceChildren(metric('Harmonized activity',p.index.toFixed(1),'MODIS-scale seasonal index'),metric('Historical context',p.state,p.percentile===null?'Needs five comparable years':p.percentile.toFixed(0)+'th percentile · '+p.n+' comparison years'),metric('Seasonal median',p.median===null?'—':p.median.toFixed(1),p.ratio===null?'Ratio unavailable':p.ratio.toFixed(2)+'× seasonal median'),metric('Active-fire cells',p.cells.toLocaleString(),p.coveredDays+'/'+p.daysInMonth+' days with source coverage'));
 $('comparison').replaceChildren(...[['MODIS source detections',p.modisRaw],['VIIRS source detections',p.viirsRaw],['MODIS occupied cells',p.modisCells],['VIIRS occupied cells (all products)',p.allViirsCells],['Reference VIIRS occupied cells',p.viirsCells],['Cells shared by sensors',p.shared]].map(([label,n])=>metric(label,n.toLocaleString(),'Quality filters applied · '+month)));
 const coefficient=slot=>result.model.months?.[slot]?.[p.month.slice(5,7)]?.factor??result.model.factors[slot]?.factor;const f=coefficient(p.reference);const agreement=metric('Sensor agreement',p.cells?(100*p.shared/p.cells).toFixed(1)+'%':'—','Shared / union daily cells; not accuracy');$('comparison').append(agreement);$('comparison-note').textContent='Higher VIIRS counts reflect finer resolution and sensitivity. '+(f!==null&&f!==undefined?'Monthly reference VIIRS uses '+p.references.map(slot=>({s:'S-NPP',j:'NOAA-20',n:'NOAA-21'})[slot]+' × '+coefficient(slot).toFixed(3)).join('; ')+' before combination.':'A VIIRS calibration is unavailable for this period.')+' Historical maps show common cell centers with original source counts attached; raw point coordinates stay offline.';
 $('period-details').textContent=month+' · '+(p.provisional?'provisional NRT · ':'')+(p.complete?'complete month':'partial coverage: '+p.coveredDays+' days')+' · '+p.state+'. Percentile compares the same calendar month and exact covered dates in other years; the selected year is excluded. This measures relative burning activity, not disaster severity or future risk.';
 $('export').disabled=false;if($('basemap').value==='daily'&&map.getContainer().dataset.imageryDate!==[month+'-15',new Date().toISOString().slice(0,10)].sort()[0])setBasemap('daily');renderCalendar();await draw();const u=new URL(location.href);u.searchParams.set('case',caseID);u.searchParams.set('month',month);u.searchParams.set('view',view);history.replaceState(null,'',u);u.searchParams.set('from',String($('history-from').value));u.searchParams.set('to',String($('history-to').value));u.searchParams.set('recent',$('include-recent').checked?'1':'0');u.searchParams.set('basemap',$('basemap').value);u.searchParams.set('detections',visible?'1':'0');if(area.bounds)u.searchParams.set('area',area.bounds.join(','));else u.searchParams.delete('area');if(boundaries.country)u.searchParams.set('country',boundaries.country.properties.country);else u.searchParams.delete('country');if(boundary&&boundary.id!==boundaries.country?.id)u.searchParams.set('admin1',boundary.id);else u.searchParams.delete('admin1');history.replaceState(null,'',u);const large=new URL(u);large.searchParams.set('large','1');$('map-page-link').href=large.href;
 const brief={selected:p.cells,bars:[['MODIS',p.modisRaw],['VIIRS',p.viirsRaw]],raw:p.modisRaw+p.viirsRaw,cells:p.cells,overlap:p.shared,latest:null,maxFrp:null};shell.showSummary(brief);boundaries.showSummary(brief,{start:month+'-01',end:month+'-'+p.daysInMonth,confidence:40,view,day:null});if(boundary){const note=document.createElement('p');note.className='history-scope';note.textContent='Historical coverage is limited to the '+result.case.name+' archive and its populated months. These are not complete country or region totals.';$('boundary-info').append(note);}
 }catch(error){$('status').textContent=error.message+'. Last successfully loaded historical values are retained; no synthetic values are substituted.';}
}
async function analyze({fit=false}={}){
 if(!metadata)return;const id=++query;++selection;++drawID;$('status').textContent='Loading compact historical summaries…';$('export').disabled=true;
 try{const next=await ask('analyze',{caseID,fromYear:Number($('history-from').value),toYear:Number($('history-to').value),area:area.bounds,boundary,includeRecent:$('include-recent').checked});if(id!==query||next.stale)return;result=next;
 $('history-title').textContent=next.case.name;$('history-provenance').textContent=($('include-recent').checked?'NASA FIRMS Standard Processing + separately labeled provisional NRT · ':'NASA FIRMS Standard Processing archives · ')+next.case.subtitle+' · historical build '+new Date(next.build).toISOString().slice(0,16).replace('T',' ')+' UTC'+(next.offline?' · cached offline record':'');
 $('status').textContent=next.months.length?'Loaded '+next.days.toLocaleString()+' covered daily records within the '+next.case.name+' archive. Areas outside this case are not included. '+next.quality.description:'No historical coverage for this selected area or date range. Choose a case study or clear the area.';
 if(!next.months.some(m=>m.month===month))month=next.months.find(m=>m.month===next.case.defaultMonth)?.month||next.months.at(-1)?.month;
 renderCalendar();modelDescription();if(fit){const b=next.case.bounds;map.fitBounds([[b[1],b[0]],[b[3],b[2]]],{padding:[30,40],animate:window.atlasMotion.enabled});}
 if(month){await select();}else{$('metrics').replaceChildren(metric('Historical coverage','Unavailable','Missing coverage is never treated as zero'));hotspots.paint([]);$('comparison').replaceChildren();$('period-details').textContent='No source coverage for this selection.';}
 }catch(error){$('status').textContent=error.message+'. Showing the last successful historical analysis, if available.';}
}
$('history-case').onchange=()=>{caseID=$('history-case').value;$('history-from').value=metadata.cases.find(c=>c.id===caseID).years[0];$('history-to').value=metadata.recentSnapshot?metadata.recentSnapshot.dateEnd.slice(0,4):metadata.cases.find(c=>c.id===caseID).years.at(-1);boundary=null;boundaries.clear({notify:false});area.clear({notify:false});month=null;analyze({fit:true});};
$('include-recent').onchange=()=>analyze();
$('history-from').onchange=$('history-to').onchange=()=>{if(Number($('history-from').value)>Number($('history-to').value)){$('status').textContent='Choose a valid year range.';return;}analyze();};
document.querySelectorAll('[data-view]').forEach(b=>{b.classList.toggle('selected',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));b.onclick=()=>{view=b.dataset.view;document.querySelectorAll('[data-view]').forEach(x=>{x.classList.toggle('selected',x===b);x.setAttribute('aria-pressed',String(x===b));});select();};});
$('reset').onclick=()=>{month=result?.months.at(-1)?.month;select();};
$('world-view').textContent='Case study view';$('world-view').onclick=()=>{boundary=null;boundaries.clear({notify:false});area.clear({notify:false});analyze({fit:true});};
$('export').onclick=async()=>{const csv=await ask('export'),url=URL.createObjectURL(new Blob([csv],{type:'text/csv'})),a=document.createElement('a');a.href=url;a.download='ember-atlas-history-'+caseID+'-'+month+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const panel=document.querySelector('.map-panel'),parent=panel.parentNode,next=panel.nextSibling;
$('enlarge-map').onclick=()=>{expanded=!expanded;shell.setExpanded(expanded);if(expanded){document.body.append(panel);document.body.classList.add('map-expanded');panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');}else{parent.insertBefore(panel,next);document.body.classList.remove('map-expanded');panel.removeAttribute('role');panel.removeAttribute('aria-modal');}$('enlarge-map').textContent=expanded?'↙ Close large map':'↗ Enlarge map';$('enlarge-map').setAttribute('aria-expanded',String(expanded));(expanded?$('sidebar-toggle'):$('enlarge-map')).focus();requestAnimationFrame(resize);};
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&expanded)$('enlarge-map').click();if(e.key==='Tab'&&expanded){const nodes=[...panel.querySelectorAll('button,select,a[href],input')].filter(n=>n.offsetParent!==null),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});
window.addEventListener('atlas-motion-change',draw);
try{metadata=await ask('metadata');if(!metadata.cases.some(c=>c.id===caseID))caseID=metadata.cases[0]?.id;
 $('history-case').replaceChildren(...metadata.cases.map(c=>{const o=document.createElement('option');o.value=c.id;o.textContent=c.name;return o;}));$('history-case').value=caseID;
 const years=[...new Set([...metadata.cases.flatMap(c=>c.years),...(metadata.recentSnapshot?[Number(metadata.recentSnapshot.dateEnd.slice(0,4))]:[])])].sort((a,b)=>a-b);for(const id of ['history-from','history-to'])$(id).replaceChildren(...years.map(y=>{const o=document.createElement('option');o.value=o.textContent=y;return o;}));const config=metadata.cases.find(c=>c.id===caseID);$('history-from').value=years.includes(Number(params.get('from')))?params.get('from'):config.years[0];$('history-to').value=years.includes(Number(params.get('to')))?params.get('to'):years.at(-1);$('include-recent').checked=params.get('recent')!=='0';
 $('case-buttons').replaceChildren(...metadata.cases.map(c=>{const b=document.createElement('button');b.textContent='Explore '+c.name;b.onclick=()=>{$('history-case').value=c.id;$('history-case').onchange();};return b;}));
 await analyze({fit:!area.bounds});if(area.bounds){const b=area.bounds;map.fitBounds([[b[1],b[0]],[b[3],b[2]]],{animate:false,padding:[30,40]});}if(params.get('country')){const ready=await boundaries.ready;if(ready){await boundaries.selectCountry(params.get('country'));if(params.get('admin1')){$('region-picker').value=params.get('admin1');$('region-picker').dispatchEvent(new Event('change'));}}}if(params.get('large')==='1')$('enlarge-map').click();
}catch{$('status').textContent='Historical archives are unavailable. Run the historical preprocessing pipeline or use Live mode. No demonstration data is injected.';}

let refreshing=false;async function checkHistory(){if(document.hidden||refreshing||!metadata)return;refreshing=true;try{const r=await ask('refresh');if(r.changed){metadata=r.metadata;await analyze();}else if(r.offline)$('status').textContent='Update unavailable. Keeping the cached real historical record.';}catch{$('status').textContent='History update unavailable. Last successful values remain visible.';}finally{refreshing=false;}}
setInterval(checkHistory,60000);document.addEventListener('visibilitychange',()=>{if(!document.hidden)checkHistory();});
