// Move the existing controls, preserving their listeners and IDs, into one map sidebar.
export function createMapShell(panel,{keepOutside=[]}={}){
 const fullPage=document.body.classList.contains('map-page');
 const sidebar=document.createElement('aside');sidebar.className='explorer-sidebar';sidebar.id='explorer-sidebar';sidebar.setAttribute('aria-label','Map controls and NASA data');sidebar.setAttribute('data-lenis-prevent','');
 sidebar.innerHTML='<header class="explorer-brand"><span class="symbol">✳</span><div><strong>EMBER ATLAS</strong><small>EARTH OBSERVATION EXPLORER</small></div></header><section class="boundary-tools"><label for="country-search">Find a country or territory</label><form id="country-search-form"><input id="country-search" list="country-names" placeholder="Search in English" autocomplete="off"><button type="submit">Go</button></form><datalist id="country-names"></datalist><p id="boundary-status" role="status">Loading country borders…</p><div id="boundary-breadcrumb" class="boundary-breadcrumb"></div><section id="boundary-info" class="boundary-info" aria-label="Selected boundary NASA summary" aria-live="polite"><h3>Explore the world</h3><p>Double-click a country to see its regions and NASA observations. Double-click a region to focus on it.</p></section><label for="region-picker">Regions of selected country</label><select id="region-picker" disabled><option>Select a country first</option></select><button id="boundary-back" type="button" hidden>← Back to country</button><button id="boundary-clear" type="button" hidden>Clear boundary</button></section>';
 const oldHead=panel.querySelector('.panel-head'),tabs=oldHead.querySelector('.tabs'),toolbar=panel.querySelector('.map-toolbar'),enlarge=document.getElementById('enlarge-map'),link=document.getElementById('map-page-link');
 const top=document.createElement('header');top.className='explorer-topbar';top.innerHTML='<div><span class="mini-label">NASA FIRMS / LIVE OBSERVATIONS</span><h2>Global observatory</h2></div><div class="embedded-tools"><button id="embedded-select" type="button">Select area</button></div>';top.querySelector('.embedded-tools').append(enlarge);oldHead.replaceWith(top);
 const controls=document.createElement('section');controls.className='explorer-controls';controls.innerHTML='<h3>Map &amp; observation filters</h3>';controls.append(tabs,toolbar);
 sidebar.append(controls);
 const area=document.getElementById('area-status'),imagery=document.getElementById('imagery-note'),accessible=panel.querySelector('.map-accessible');sidebar.append(area,imagery);
 const originals=[], move=element=>{if(!element)return;const slot=document.createComment('Map control location');element.before(slot);originals.push({element,slot});sidebar.append(element);};
 const feed=document.querySelector('.feed-bar'),status=document.getElementById('status'),filters=document.querySelector('.filters'),metrics=document.getElementById('metrics'),activity=document.getElementById('activity'),exportButton=document.getElementById('export');
 const dataHeading=document.createElement('h3');dataHeading.textContent='NASA observations';sidebar.append(dataHeading);
 const activityNodes=activity&&keepOutside.length?[...activity.children].filter(node=>!keepOutside.includes(node)):[activity];
 const dataNodes=[feed,status,filters,metrics,...activityNodes,exportButton,document.getElementById('motion-toggle')];
 sidebar.append(accessible);
 const frame=document.createElement('div');frame.className='explorer-frame';
 const stage=document.createElement('div');stage.className='explorer-stage';
 const map=document.getElementById('map');stage.append(map);
 const floating=document.createElement('div');floating.className='explorer-floating';floating.innerHTML='<button id="sidebar-toggle" type="button" aria-controls="explorer-sidebar" aria-expanded="true" title="Collapse map sidebar">‹</button><span class="map-guidance">Double-click country → region</span><button id="map-exit" type="button">Close map ×</button>';stage.append(floating);
 const overlayToggle=document.createElement('button');overlayToggle.type='button';overlayToggle.id='detections-toggle';overlayToggle.className='map-overlay-toggle';overlayToggle.textContent='Hide detections';overlayToggle.setAttribute('aria-pressed','false');overlayToggle.setAttribute('aria-controls','map');stage.append(overlayToggle);
 const boundaryNav=document.createElement('div');boundaryNav.className='map-boundary-nav';boundaryNav.hidden=true;boundaryNav.innerHTML='<button id="map-boundary-back" type="button">← Back</button><span id="map-boundary-name"></span><button id="map-boundary-close" type="button" aria-label="Clear boundary selection" title="Clear boundary selection">×</button>';stage.append(boundaryNav);
 boundaryNav.querySelector('#map-boundary-back').onclick=()=>document.getElementById('boundary-back').click();boundaryNav.querySelector('#map-boundary-close').onclick=()=>document.getElementById('boundary-clear').click();
 const density=document.getElementById('map-density');density.classList.add('explorer-density');stage.append(density);
 const notice=document.createElement('button');notice.type='button';notice.className='embedded-selection';notice.hidden=true;notice.title='Enlarge map to inspect selected country';const insight=document.createElement('section');insight.className='embedded-insight';insight.hidden=true;const compactSummary=document.createElement('p');compactSummary.setAttribute('role','status');insight.append(notice,compactSummary);stage.append(insight);
 const footer=panel.querySelector('.map-footer');footer.innerHTML='<span><i class="dot orange"></i> MODIS <i class="dot blue"></i> VIIRS <i class="dot green"></i> Harmonized</span><span>NASA FIRMS · English labels · <a href="https://www.naturalearthdata.com/" target="_blank" rel="noopener">Natural Earth</a></span>';
 sidebar.append(link);frame.append(sidebar,stage);panel.insertBefore(frame,footer);
 let expanded=false,collapsed=false,transferred=false;
 function transfer(on){if(on===transferred)return;transferred=on;if(on){for(const el of dataNodes)move(el);}else{for(const {element,slot} of originals)slot.replaceWith(element);originals.length=0;}}
 function setExpanded(value){expanded=value;panel.classList.toggle('explorer-full',value||fullPage);transfer(value||fullPage);document.getElementById('map-exit').textContent=fullPage?'← Observatory':'Close map ×';document.getElementById('map-exit').onclick=fullPage?()=>location.assign(link.href):()=>enlarge.click();}
 if(fullPage)setExpanded(true);
 const shortcut=document.getElementById('embedded-select'),selection=document.getElementById('select-area');shortcut.onclick=()=>selection.click();new window.MutationObserver(()=>shortcut.textContent=selection.textContent).observe(selection,{childList:true});
 const clear=document.createElement('button');clear.type='button';clear.textContent='Clear area';clear.hidden=true;top.querySelector('.embedded-tools').prepend(clear);const originalClear=document.getElementById('clear-area');clear.onclick=()=>originalClear.click();new window.MutationObserver(()=>clear.hidden=originalClear.hidden).observe(originalClear,{attributes:true,attributeFilter:['hidden']});
 function collapse(){collapsed=!collapsed;panel.classList.toggle('sidebar-collapsed',collapsed);const b=document.getElementById('sidebar-toggle');b.textContent=collapsed?'›':'‹';b.setAttribute('aria-expanded',String(!collapsed));requestAnimationFrame(()=>map.dispatchEvent(new window.Event('atlas-map-layout')));}
 document.getElementById('sidebar-toggle').onclick=collapse;
 notice.onclick=()=>enlarge.click();
 return {setExpanded,showSelection(name,{backLabel='Back to world'}={}){notice.hidden=!name;insight.hidden=!name;boundaryNav.hidden=!name;document.getElementById('map-boundary-name').textContent=name||'';const back=document.getElementById('map-boundary-back');back.textContent='← '+backLabel;back.title=backLabel;notice.textContent=name?name+' · View details ↗':'';compactSummary.textContent=name?'Analyzing NASA observations…':'';},showSummary(result){if(!insight.hidden)compactSummary.textContent=result.selected.toLocaleString()+' selected detections · '+result.bars[0][1].toLocaleString()+' MODIS / '+result.bars[1][1].toLocaleString()+' VIIRS observations in the date window';},get expanded(){return expanded||fullPage;}};
}
