import {createBoundaryExplorer} from './boundary-explorer.js';
import {mapOptions,tileOptions,minimumWorldZoom} from './map-policy.js';import {basemaps,imageryDate} from './basemaps.js';import {validateDrawnPolygon} from './monitor-aoi.js';import {focusBounds,geometryPolygons,ringBounds} from './boundary-geometry.js';

// Use the same explorer surfaces and sidebar proportions as Sensors / Analyze.
export function createMonitorShell(){
 const $=id=>document.getElementById(id),panel=document.querySelector('.monitor-map-panel'),sidebar=document.querySelector('.priority-panel'),stage=document.querySelector('.monitor-map-frame');
 sidebar.classList.add('monitor-sidebar','explorer-sidebar');sidebar.setAttribute('data-lenis-prevent','');
 const brand=document.createElement('header');brand.className='explorer-brand';brand.innerHTML='<span class="symbol">✳</span><div><strong>EMBER ATLAS</strong><small>GLOBAL ACTIVITY MONITOR</small></div>';sidebar.prepend(brand);
 const selection=document.querySelector('.monitor-selection');brand.after(selection);
 const boundary=document.createElement('details');boundary.className='boundary-tools';boundary.innerHTML='<summary>Countries &amp; regions</summary><label for="country-search">Find a country or territory</label><form id="country-search-form"><input id="country-search" list="country-names" placeholder="Search in English" autocomplete="off"><button type="submit">Go</button></form><datalist id="country-names"></datalist><p id="boundary-status" role="status">Loading country borders…</p><div id="boundary-breadcrumb" class="boundary-breadcrumb"></div><section id="boundary-info" class="boundary-info" aria-live="polite"><h3>Explore the world</h3><p>Double-click a country, then a region, to inspect observations.</p></section><label for="region-picker">Regions of selected country</label><select id="region-picker" disabled><option>Select a country first</option></select><button id="boundary-back" hidden>← Back to world</button><button id="boundary-clear" hidden>Clear boundary</button>';
 selection.after(boundary);
 const options=document.createElement('details');options.className='monitor-map-options';options.innerHTML='<summary>Map layers &amp; evidence</summary>';
 const settings=document.querySelector('.monitor-map-settings');settings.lastElementChild.remove();options.append(settings);
 const controls=document.querySelector('.monitor-map-controls'),hide=$('monitor-hide');const floating=document.createElement('div');floating.className='monitor-floating';floating.innerHTML='<button id="monitor-sidebar-toggle" aria-controls="monitor-sidebar" aria-expanded="true" aria-label="Collapse map sidebar">‹</button><button id="monitor-world-view">World view</button>';floating.append(hide);stage.append(floating);
 sidebar.id='monitor-sidebar';controls.className='monitor-sidebar-controls';options.append(controls);boundary.after(options);
 options.after(document.querySelector('.monitor-playback'));
 const metrics=$('monitor-metrics');sidebar.querySelector('.monitor-playback').after(metrics);
 const detail=$('monitor-event-detail');metrics.after(detail);
 const attention=document.createElement('section');attention.id='monitor-attention-view';attention.setAttribute('aria-label','Areas requiring attention');
 for(const node of [...sidebar.children])if(![brand,selection,boundary,options,metrics,detail].includes(node)&&!node.classList.contains('monitor-playback')&&!node.classList.contains('watchlist-panel')&&!node.classList.contains('alert-panel'))attention.append(node);
 attention.querySelector('.priority-search').after(detail);
 const controlView=document.createElement('section');controlView.id='monitor-controls-view';controlView.setAttribute('aria-label','Area, map and playback controls');
 for(const node of [...sidebar.children])if(node!==brand)controlView.append(node);
 const tabs=document.createElement('div');tabs.className='monitor-sidebar-tabs';tabs.setAttribute('role','group');tabs.setAttribute('aria-label','Sidebar view');
 tabs.innerHTML='<button id="monitor-attention-tab" aria-controls="monitor-attention-view" aria-pressed="true">Attention</button><button id="monitor-controls-tab" aria-controls="monitor-controls-view" aria-pressed="false">Map controls</button>';
 sidebar.append(tabs,attention,controlView);controlView.hidden=true;
 function showView(controls){attention.hidden=controls;controlView.hidden=!controls;$('monitor-attention-tab').setAttribute('aria-pressed',String(!controls));$('monitor-controls-tab').setAttribute('aria-pressed',String(controls));sidebar.scrollTop=0;}
 $('monitor-attention-tab').onclick=()=>showView(false);$('monitor-controls-tab').onclick=()=>showView(true);
 const frame=document.createElement('div');frame.className='monitor-explorer-frame';frame.append(sidebar,stage);panel.append(frame);document.querySelector('.monitor-layout').append(panel);
 const note=$('monitor-map-note');note.classList.add('explorer-density');stage.append(note);
 const back=document.createElement('button');back.id='monitor-boundary-back';back.textContent='← Back';back.hidden=true;back.onclick=()=>$('boundary-back').click();$('monitor-map-selection').prepend(back);
 function collapse(value){panel.classList.toggle('sidebar-collapsed',value);const b=$('monitor-sidebar-toggle');b.textContent=value?'›':'‹';b.setAttribute('aria-expanded',String(!value));b.setAttribute('aria-label',value?'Expand map sidebar':'Collapse map sidebar');requestAnimationFrame(()=>$('monitor-map').dispatchEvent(new Event('atlas-map-layout')));}
 $('monitor-sidebar-toggle').onclick=()=>collapse(!panel.classList.contains('sidebar-collapsed'));
 return {showControls(){collapse(false);showView(true);},showDetail(){collapse(false);showView(false);sidebar.scrollTop+=detail.getBoundingClientRect().top-sidebar.getBoundingClientRect().top-tabs.getBoundingClientRect().height-12;},closeDetail(){showView(false);sidebar.querySelector('.priority-search').scrollIntoView({block:'nearest',behavior:'instant'});}};
}

export function createMonitorMap({ask,onInspect,onArea,onNotice,onArchive}){
 const $=id=>document.getElementById(id),map=L.map('monitor-map',{...mapOptions,zoomSnap:.25,zoomAnimation:window.atlasMotion.enabled,fadeAnimation:window.atlasMotion.enabled}).setView([15,15],2);map.zoomControl.setPosition('bottomright');
 const canvas=document.createElement('canvas');canvas.className='monitor-leaflet-canvas leaflet-zoom-hide';map.getPane('overlayPane').append(canvas);let footprintMode='latest',layers=[],visible=true,selected=null,view='Harmonized',drawTicket=0,busy=false,queued=false,positions=[],draft=null,areaOutline=null,mode=null,corners=[],restoreZoom=false,baseTicket=0;
 let archive=null,archiveRPC=0,archivePending=new Map(),archiveWorker=null;
 function archiveQuery(args){archiveWorker??=new Worker(new URL('./global-history-worker.js',import.meta.url),{type:'module'});archiveWorker.onmessage=({data})=>{const p=archivePending.get(data.id);if(p){archivePending.delete(data.id);data.error?p.reject(Error(data.error)):p.resolve(data.result);}};archiveWorker.onerror=()=>{for(const p of archivePending.values())p.reject(Error('Archive decoder unavailable'));archivePending.clear();};return new Promise((resolve,reject)=>{const id=++archiveRPC;archivePending.set(id,{resolve,reject});archiveWorker.postMessage({id,args});});}
 const locationControl=L.control({position:'bottomright'});locationControl.onAdd=()=>{const button=L.DomUtil.create('button','monitor-location-toggle');button.type='button';button.textContent='Location pins: on';button.setAttribute('aria-pressed','true');L.DomEvent.disableClickPropagation(button);button.onclick=()=>{showLocations=!showLocations;button.textContent='Location pins: '+(showLocations?'on':'off');button.setAttribute('aria-pressed',String(showLocations));draw();};return button;};let showLocations=true;locationControl.addTo(map);
 const pane=map.createPane('monitorAreas');pane.style.zIndex='420';
 function viewport(){const b=map.getBounds();return [b.getWest(),b.getSouth(),b.getEast(),b.getNorth()];}
 async function draw(){queued=true;drawTicket++;if(busy)return;busy=true;try{while(queued){queued=false;const ticket=drawTicket;if(!visible){canvas.style.visibility='hidden';positions=[];$('monitor-map-note').textContent='Data overlays hidden. Map navigation remains available; Show overlays restores the selected evidence view.';continue;}let records,points=[],archiveInfo=null;if(archive){const a=await archiveQuery({date:archive.date,bounds:viewport(),zoom:map.getZoom(),polygon:archive.polygon});if(ticket!==drawTicket)continue;archiveInfo=a;points=a.rows.filter(r=>!['MODIS','VIIRS'].includes(view)||r.sensor===view).map(r=>({...r,point:true}));records=[];onArchive?.({...a,date:archive.date,count:points.length});}else{[records,points]=await Promise.all([ask('geometry',{id:null,view,bounds:viewport(),footprintMode}),showLocations?ask('geometry',{locations:true,bounds:viewport()}):Promise.resolve([])]);}if(ticket!==drawTicket)continue;const size=map.getSize(),ratio=Math.min(devicePixelRatio,1.5),position=map.containerPointToLayerPoint([0,0]);L.DomUtil.setPosition(canvas,position);canvas.width=Math.round(size.x*ratio);canvas.height=Math.round(size.y*ratio);canvas.style.width=size.x+'px';canvas.style.height=size.y+'px';const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);canvas.style.visibility='';positions=[];const colors={Critical:'#ff788d',Elevated:'#ffa86b',Watch:'#efcf87',Normal:'#a5e6bc','Insufficient history':'#80c5fa',MODIS:'#ff965c',VIIRS:'#77bfff'},pixels=new Map();
   for(const r of records){const a=map.latLngToContainerPoint([r.bounds[3],r.bounds[0]]),b=map.latLngToContainerPoint([r.bounds[1],r.bounds[2]]);if(b.x<0||a.x>size.x||b.y<0||a.y>size.y)continue;const x=a.x,y=a.y,w=Math.max(1,b.x-a.x),h=Math.max(1,b.y-a.y);const key=map.getZoom()<8?Math.floor(x)+':'+Math.floor(y)+':'+(r.view==='Harmonized'?r.state:r.view):null;if(key&&pixels.has(key))continue;if(key)pixels.set(key,true);positions.push({x,y,w,h,id:r.eventID});ctx.fillStyle=colors[r.view==='Harmonized'?r.state:r.view]||'#8ac9ff';ctx.globalAlpha=selected===r.eventID?.8:.4;ctx.fillRect(x,y,w,h);if(selected===r.eventID&&w>4){ctx.globalAlpha=.9;ctx.strokeStyle='#effaff';ctx.strokeRect(x,y,w,h);}}
   const bins=new Set(),labels=new Set();if(showLocations)for(const r of points){const p=map.latLngToContainerPoint([r.lat,r.lon]);if(p.x<0||p.x>size.x||p.y<0||p.y>size.y)continue;const bin=Math.floor(p.x/10)+':'+Math.floor(p.y/10);if(bins.has(bin))continue;bins.add(bin);ctx.globalAlpha=1;ctx.fillStyle=r.sensor==='MODIS'?'#ff965c':'#79c4ff';ctx.strokeStyle='#071321';ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(p.x,p.y,3.5,0,Math.PI*2);ctx.fill();ctx.stroke();positions.push({x:p.x-4,y:p.y-4,w:8,h:8,id:r.eventID,location:r});if(map.getZoom()>=9){const box=Math.floor(p.x/165)+':'+Math.floor(p.y/30);if(labels.has(box))continue;labels.add(box);ctx.font='12px system-ui';const text=String(r.lat)+', '+String(r.lon),w=ctx.measureText(text).width;ctx.fillStyle='#081827';ctx.fillRect(p.x+7,p.y-12,w+10,20);ctx.fillStyle='#e7f4ff';ctx.fillText(text,p.x+12,p.y+2);}}
   if(archive){$('monitor-map-note').textContent=(archiveInfo.unavailable?'No NASA coverage catalogued for this day. ':archiveInfo.failed?'PARTIAL DATA · '+archiveInfo.failed+' archive tiles failed. ':'')+points.length.toLocaleString()+' NASA archived detections in the viewport · '+archive.date+' UTC · click a pin for coordinates and original sensor details. Nearby pins share a screen pixel at low zoom. Missing coverage does not establish absence of fire.';continue;}
   $('monitor-map-note').textContent=records.length.toLocaleString()+' observed '+(view==='Harmonized'?'footprint-support cells':'raw approximate satellite pixels')+' in this view · '+(footprintMode==='latest'?'latest acquisition per activity':'all observed support through the selected time')+'. Subpixel support overlaps share a display pixel. Not burned area or interpolated fire perimeter.';
  }}catch(error){onNotice('Map geometry unavailable: '+error.message);}finally{busy=false;}}
 map.on('moveend',draw);map.on('zoomstart',()=>canvas.style.visibility='hidden');map.on('click',e=>{if(mode){corners.push([e.latlng.lng,e.latlng.lat]);paintDraft();if(mode==='rectangle'&&corners.length===2)finishDrawing();return;}if(!visible)return;const p=e.containerPoint;let best=positions.findLast(r=>p.x>=r.x-3&&p.x<=r.x+r.w+3&&p.y>=r.y-3&&p.y<=r.y+r.h+3);if(best?.id){if(best.location)locate(best.location);onInspect(best.id);}if(best?.location)showLocation(best.location,L.latLng(best.location.lat,best.location.lon));});
 async function setBase(name){const id=++baseTicket;map.getContainer().dataset.vectorReady='false';map.fire('basemapchange');for(const layer of layers)map.removeLayer(layer);layers=[];const config=basemaps[name]||basemaps.satellite,date=imageryDate(new Date().toISOString().slice(0,10));const raster=config.vector?basemaps.satellite:config;layers.push(L.tileLayer(raster.url.replace('{date}',date),{...tileOptions,maxNativeZoom:raster.maxNativeZoom,attribution:raster.attribution}).addTo(map));if(config.vector)try{const {createVectorBasemap}=await import('./vector-basemap.js');const layer=await createVectorBasemap(name);if(id!==baseTicket)return;layer.addTo(map);for(const old of layers)map.removeLayer(old);layers=[layer];map.getContainer().dataset.vectorReady='true';map.fire('basemapchange');map.attributionControl.addAttribution(config.attribution);}catch{onNotice('Street renderer unavailable; satellite imagery retained.');}}
 $('monitor-basemap').onchange=()=>setBase($('monitor-basemap').value);setBase('satellite');$('monitor-footprints').onchange=()=>{footprintMode=$('monitor-footprints').value;draw();};$('monitor-view').onchange=()=>{view=$('monitor-view').value;draw();};$('monitor-hide').onclick=()=>{visible=!visible;$('monitor-hide').textContent=visible?'Hide overlays':'Show overlays';$('monitor-hide').setAttribute('aria-pressed',String(!visible));draw();};
 function fit(bounds){map.fitBounds([[Math.max(-85,bounds[1]),bounds[0]],[Math.min(85,bounds[3]),bounds[2]]],{padding:[40,55],maxZoom:13,animate:window.atlasMotion.enabled});}
 function clearDraft(){if(draft)map.removeLayer(draft);draft=null;}
 function paintDraft(){clearDraft();if(mode==='rectangle'&&corners.length===1)draft=L.circleMarker([corners[0][1],corners[0][0]],{radius:4,color:'#9dd3ff'}).addTo(map);else if(corners.length>1)draft=L.polyline(corners.map(([x,y])=>[y,x]),{color:'#8bcaff',weight:2,dashArray:'5 5'}).addTo(map);$('monitor-draw-polygon').textContent=mode==='polygon'?'Finish polygon ('+corners.length+' points)':'Draw polygon';}
 function stopDrawing(){mode=null;corners=[];clearDraft();if(restoreZoom)map.doubleClickZoom.enable();$('monitor-draw-rectangle').textContent='Draw rectangle';$('monitor-draw-polygon').textContent='Draw polygon';}
 function startDrawing(kind){if(mode===kind){if(kind==='polygon'&&corners.length>=3)finishDrawing();else stopDrawing();return;}stopDrawing();mode=kind;restoreZoom=map.doubleClickZoom.enabled();map.doubleClickZoom.disable();$('monitor-draw-rectangle').textContent=kind==='rectangle'?'Cancel rectangle':'Draw rectangle';onNotice(kind==='rectangle'?'Choose two opposite corners on the map. Escape cancels.':'Click polygon vertices, then Finish polygon. Escape cancels.');}
 function finishDrawing(){const kind=mode,points=corners.slice();if(kind==='polygon'&&points.length<3){onNotice('A polygon needs at least three vertices.');return;}let geometry;if(kind==='rectangle'){const [a,b]=points,w=Math.min(a[0],b[0]),s=Math.min(a[1],b[1]),e=Math.max(a[0],b[0]),n=Math.max(a[1],b[1]);if(e-w<1e-7||n-s<1e-7){onNotice('Choose an area with width and height.');stopDrawing();return;}geometry={type:'Polygon',coordinates:[[[w,s],[e,s],[e,n],[w,n],[w,s]]]};}else{try{validateDrawnPolygon(points);}catch(error){onNotice(error.message);return;}geometry={type:'Polygon',coordinates:[[...points,points[0]]]};}stopDrawing();boundaries.clear({notify:false});setArea(geometry,'Custom Area of Interest');onArea({bounds:focusBounds(geometry),polygon:geometry,name:'Custom Area of Interest'});}
 function updateSelection(name){$('monitor-map-selection').hidden=!name;$('monitor-area-name').textContent=name||'Custom Area of Interest';$('monitor-clear-area').hidden=!name;}
 function setArea(geometry,name){if(!geometry)boundaries?.clear({notify:false});if(areaOutline)map.removeLayer(areaOutline);areaOutline=geometry?L.geoJSON({type:'Feature',geometry},{pane:'monitorAreas',style:{color:'#91cfff',weight:2,fillOpacity:.05}}).addTo(map):null;updateSelection(geometry?name:null);$('monitor-boundary-back').hidden=!boundaries?.selected;}
 $('monitor-draw-rectangle').onclick=()=>startDrawing('rectangle');$('monitor-draw-polygon').onclick=()=>startDrawing('polygon');$('monitor-map-clear').onclick=()=>{const hadBoundary=!!boundaries.selected;stopDrawing();setArea(null);onArea(hadBoundary?{caseID:'world',name:'Worldwide'}:null);};$('monitor-clear-area').onclick=()=>$('monitor-map-clear').click();document.addEventListener('keydown',e=>{if(e.key==='Escape'&&mode){e.preventDefault();stopDrawing();}});
 const panel=document.querySelector('.monitor-map-panel'),anchor=document.createComment('Map home'),main=document.querySelector('main'),navigation=document.querySelector('.site-nav');panel.before(anchor);const inspectLink=document.createElement('button');inspectLink.className='monitor-map-inspect';inspectLink.textContent='View selected activity details ↗';inspectLink.hidden=true;document.querySelector('.monitor-map-frame').append(inspectLink);inspectLink.onclick=()=>{if(large)$('monitor-map-enlarge').click();$('monitor-event-detail').scrollIntoView({behavior:'instant',block:'start'});};let large=false,originalFocus=null;$('monitor-map-enlarge').onclick=()=>{large=!large;panel.classList.toggle('map-large',large);document.body.classList.toggle('monitor-map-open',large);document.documentElement.classList.toggle('monitor-map-open',large);$('monitor-map-enlarge').textContent=large?'× Close large map':'↗ Enlarge map';$('monitor-map-enlarge').setAttribute('aria-expanded',String(large));if(large){originalFocus=document.activeElement;document.body.append(panel);main.inert=true;navigation.inert=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');$('monitor-map-enlarge').focus();}else{anchor.after(panel);main.inert=false;navigation.inert=false;panel.removeAttribute('role');panel.removeAttribute('aria-modal');originalFocus?.focus();}requestAnimationFrame(()=>{map.invalidateSize({pan:true,animate:false});draw();});};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&large&&!mode&&!e.defaultPrevented)$('monitor-map-enlarge').click();if(e.key==='Tab'&&large){const nodes=[...panel.querySelectorAll('button,select,input,a[href]')].filter(n=>n.offsetParent!==null),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});new ResizeObserver(()=>{map.invalidateSize({pan:true,animate:false});map.setMinZoom(minimumWorldZoom(map.getSize()));draw();}).observe($('monitor-map'));

 const boundaries=createBoundaryExplorer(map,{isDrawing:()=>!!mode,getPadding:()=>({padding:[35,55]}),onNotice(name,options){updateSelection(name);$('monitor-boundary-back').hidden=!name;$('monitor-boundary-back').textContent='← '+(options?.backLabel||'Back');},onClear(){if(areaOutline)map.removeLayer(areaOutline);areaOutline=null;onArea({caseID:'world',name:'Worldwide'});},onSelect(feature){stopDrawing();if(areaOutline)map.removeLayer(areaOutline);areaOutline=null;const boxes=geometryPolygons(feature.geometry).map(r=>ringBounds(r[0])),bounds=[Math.min(...boxes.map(b=>b[0])),Math.min(...boxes.map(b=>b[1])),Math.max(...boxes.map(b=>b[2])),Math.max(...boxes.map(b=>b[3]))];onArea({bounds,polygon:feature.geometry,name:feature.properties.name,caseID:feature.properties.country==='UZB'?'uzbekistan':'world'});}});
 $('monitor-world-view').onclick=()=>{stopDrawing();setArea(null);onArea({caseID:'world',name:'Worldwide'});fit([-180,-65,180,80]);};
 $('monitor-map').addEventListener('atlas-map-layout',()=>{map.invalidateSize({pan:true,animate:false});draw();});
 function showBoundarySummary(result){if(!boundaries.selected)return;const node=$('boundary-info');const title=document.createElement('h3');title.textContent=boundaries.selected.properties.name;const values=document.createElement('p');values.textContent=result.rawDetections.toLocaleString()+' quality-selected NASA observations · '+result.totalEvents.toLocaleString()+' activity groups · '+result.supportCells.toLocaleString()+' daily footprint-support cells. Seasonal history is available only where a prepared archive covers this selection.';node.replaceChildren(title,values);}

 function showLocation(r,latlng){const node=document.createElement('section');node.className='map-observation-popup';const heading=document.createElement('strong');heading.textContent=(r.sensor||'NASA')+' reported pixel center';node.append(heading);for(const text of [String(r.lat)+', '+String(r.lon),(r.date?r.date+' '+r.time+' UTC':r.acquiredAt||''),r.satellite?'Satellite: '+r.satellite:'',r.frp!==undefined?'Pixel FRP: '+r.frp+' MW':'',(r.confidence??r.confidenceRaw)!==undefined?'Native confidence: '+(r.confidence??r.confidenceRaw):'',r.version?'Processing: '+r.version:'',r.source?'NASA archive product: '+r.source:'','Pixel coordinates are not an exact building or ignition location.'])if(text){const line=document.createElement('p');line.textContent=text;node.append(line);}pixelMarker?.closeTooltip();L.popup({maxWidth:Math.min(320,map.getSize().x-45),maxHeight:Math.max(120,Math.min(230,map.getSize().y-175)),autoPanPaddingTopLeft:[20,80],autoPanPaddingBottomRight:[20,85]}).setLatLng(latlng).setContent(node).openOn(map);}
 let pixelMarker=null;
 function locate(location,{focus=true}={}){map.closePopup();pixelMarker?.remove();const label=location.kind==='group'?'Approximate activity group center':'Reported NASA pixel center';pixelMarker=L.circleMarker([location.lat,location.lon],{radius:9,color:'#fff',weight:2,fillColor:'#63b6ff',fillOpacity:.8}).addTo(map).bindTooltip(label+' · '+location.lat+', '+location.lon,{direction:'top'});const width=(location.scan||1)/(2*111.32*Math.max(.01,Math.cos(location.lat*Math.PI/180))),height=(location.track||1)/(2*111.32);if(focus)map.fitBounds([[Math.max(-85,location.lat-height),location.lon-width],[Math.min(85,location.lat+height),location.lon+width]],{padding:[40,55],maxZoom:13,animate:false});pixelMarker.openTooltip();}

 return {draw,fit,locate,setArea,showBoundarySummary,setArchive(value){archive=value;if(value)map.attributionControl.addAttribution('<a href="https://www.earthdata.nasa.gov/data/tools/global-imagery-browse-services-gibs">NASA GIBS / FIRMS archive</a>');canvas.style.visibility='hidden';positions=[];pixelMarker?.remove();map.closePopup();draw();},select(id){pixelMarker?.remove();pixelMarker=null;selected=id;inspectLink.hidden=!id;draw();},cancelDrawing:stopDrawing};
}
