import test from 'node:test';import assert from 'node:assert/strict';
import {trackEvents,eventTrend,qualityRows,supportBounds} from './event-tracking.js';
import {seasonalBaseline,distribution,monitoringState,priorityQueue,criticalPeriods} from './early-warning.js';
import {supportRows,supportDaily,encodeRaw,encodeSupport,decodeRecords,decodeSelectedRecords} from './monitor-preprocess.js';
import {createMonitorStore} from './monitor-storage.js';import {validateDrawnPolygon,validBounds} from './monitor-aoi.js';import {createMonitorEngine} from './monitor-engine.js';
const row=(id,time='00:00',lon=65,date='2024-08-01',sensor='MODIS')=>({id,time,lon,lat:41,date,sensor,product:sensor==='MODIS'?'MODIS_SP':'VIIRS_SNPP_SP',satellite:sensor==='MODIS'?'Terra':'S-NPP',scan:1,track:1,confidence:90,confidenceRaw:sensor==='MODIS'?'90':'h',daynight:'D',frp:12,version:'6.1'});
const day=(date,v,processing='SP')=>({date,m:v,s:v,j:null,n:null,cells:v,frpMax:12,shared:0,processing});
test('activity IDs survive input order, duplicate records and rolling refreshes',()=>{const rows=[row('a'),row('b','04:00'),row('c','08:00')],full=trackEvents(rows);assert.equal(full.length,1);assert.equal(trackEvents([...rows].reverse())[0].id,full[0].id);assert.equal(trackEvents([rows[1],rows[2]],full)[0].id,full[0].id);assert.equal(trackEvents([...rows,rows[0]])[0].rawDetections,3);assert.equal(full[0].acquisitionGroups,3);assert.equal(full[0].durationHours,8);});
test('event gaps split activities without declaring extinguishment; registry retains unobserved activity',()=>{const rows=[row('a'),row('b','02:00',65,'2024-08-03')];assert.equal(trackEvents(rows).length,2);const old=trackEvents([row('a')]);const retained=trackEvents([row('other','00:00',66,'2024-08-02')],old).find(e=>e.id===old[0].id);assert.ok(retained.retained);assert.ok(!JSON.stringify(retained).includes('extinguished'));});
test('adjacent components merge with lineage; separated branches split with a parent',()=>{const initial=[row('left','00:00',65),row('right','00:00',65.04)];assert.equal(trackEvents(initial).length,2);const bridge=[65,65.01,65.02,65.03,65.04].map((lon,i)=>row('bridge'+i,'04:00',lon)),merged=trackEvents([...initial,...bridge]);assert.equal(merged.length,1);assert.equal(merged[0].aliases.length,1);const split=trackEvents([...initial,...bridge,row('split-left','08:00',65),row('split-right','08:00',65.04)]);assert.equal(split.length,2);assert.ok(split.some(e=>e.parentID));});
test('native quality selection and harmonized source support preserve evidence',()=>{assert.equal(qualityRows([row('low'),{...row('v','00:00',65,'2024-08-01','VIIRS'),confidenceRaw:'l'}]).length,1);const cells=supportRows([row('m'),row('v','00:05',65,'2024-08-01','VIIRS')]);assert.ok(cells.some(c=>c.crossSensorCoincident));assert.ok(cells.every(c=>c.sourceObservationIDs.length));assert.ok(Math.abs(cells.reduce((s,c)=>s+c.evidenceWeight,0)-2)<1e-8);const b=supportBounds(cells[0]);assert.ok(b[0]<b[2]&&b[1]<b[3]);assert.deepEqual(decodeRecords(encodeRaw([row('a')]))[0].id,'a');assert.equal(decodeRecords(encodeSupport(cells)).length,cells.length);});
test('sensor coverage remains null before a product era; zero detections mean covered source only',()=>{const d=supportDaily([],[{product:'MODIS_SP',start:'2001-01-01',end:'2001-01-01',processing:'SP'}])[0];assert.equal(d.m,0);assert.equal(d.s,null);assert.equal(d.j,null);assert.equal(d.frpMax,null);});
test('baseline uses prior SP years and season; later observations cannot change current inference',()=>{const days=Array.from({length:8},(_,i)=>day((2014+i)+'-08-01',10+i));const current=day('2022-08-01',30,'NRT'),c=seasonalBaseline(days,current,{seasonDays:0});assert.equal(c.n,8);assert.equal(c.percentile,100);assert.equal(c.reference,null);const contaminated=[...days,day('2022-08-01',9999),day('2030-08-01',9999),day('2018-08-01',9999,'NRT'),day('2018-01-01',9999)];const check=seasonalBaseline(contaminated,current,{seasonDays:0});assert.deepEqual(check.references,c.references);assert.equal(check.value,c.value);assert.equal(check.percentile,c.percentile);});
test('baseline uses one independent seasonal reference per year; zero medians and insufficient history are explicit',()=>{const days=Array.from({length:6},(_,i)=>[day((2015+i)+'-07-31',0),day((2015+i)+'-08-01',0)]).flat(),c=seasonalBaseline(days,day('2022-08-01',10));assert.equal(c.n,6);assert.equal(c.ratio,null);assert.equal(c.robustZ,null);assert.equal(c.frp.available,false);assert.equal(distribution(3,[1,2,3]).available,false);assert.equal(distribution(3,[1,2,3,4,5,null,NaN]).n,5);});
test('critical monitoring requires extreme history, persistence, multiple sensors and freshness',()=>{const c={available:true,n:21,percentile:100};const evidence={persistent:true,multiSensor:true,quality:'High evidence'};assert.equal(monitoringState(c,evidence).state,'Critical');assert.equal(monitoringState({...c,n:6},evidence).state,'Elevated');assert.equal(monitoringState(c,{...evidence,ageHours:80}).state,'Elevated');assert.equal(monitoringState({available:false},evidence).state,'Insufficient history');assert.ok(monitoringState(c,{...evidence,persistent:false,trend:{state:'Rapidly increasing'},previousPercentile:96}).approaching);assert.equal(monitoringState(c,{...evidence,persistent:false,trend:{state:'Increasing'},previousPercentile:96}).approaching,false);});
test('trend requires three acquisitions and compares centroid independent of cell order',()=>{assert.equal(eventTrend(trackEvents([row('a')])[0]).state,'Unknown');const e=trackEvents([row('a'),row('b','04:00'),row('c','08:00')])[0];assert.equal(eventTrend(e).state,'Stable');assert.ok(eventTrend(e).movementKm<1e-6);e.frames[2].cells.reverse();assert.ok(eventTrend(e).movementKm<1e-6);assert.ok(eventTrend(e).frpTrend.includes('maximum pixel FRP'));});
test('critical periods require consecutive covered unusual days; gaps break runs',()=>{const past=Array.from({length:6},(_,i)=>[day((2014+i)+'-08-01',1),day((2014+i)+'-08-02',1)]).flat();const now=[day('2022-08-01',10),day('2022-08-02',10),day('2022-08-04',10)];const p=criticalPeriods([...past,...now].map(d=>({...d,s:null})),{options:{seasonDays:7}});assert.equal(p.length,1);assert.equal(p[0].days,2);assert.equal(p[0].start,'2022-08-01');});
test('priority uses measured state and stale observation suppression',()=>{const e=(id,state,stale=false)=>({id,state,stale,context:{percentile:99},durationHours:6,ageHours:stale?90:1});assert.deepEqual(priorityQueue([e('old','Critical',true),e('new','Watch'),e('high','Elevated')]).map(e=>e.id),['high','new','old']);});
test('watchlist persists across reload and only emits changed states; unavailable storage stays explicit',()=>{const data=new Map(),storage={getItem:k=>data.get(k),setItem:(k,v)=>data.set(k,v)},store=createMonitorStore(storage),a=store.monitor({caseID:'amazon',name:'Amazon'});store.update(a.id,{state:'Watch',reasons:['seasonal anomaly'],updatedAt:'2024-08-01'});store.update(a.id,{state:'Watch',updatedAt:'2024-08-02'});assert.equal(createMonitorStore(storage).alerts.length,1);assert.equal(createMonitorStore(storage).areas[0].state,'Watch');const denied=createMonitorStore({getItem(){throw Error();},setItem(){throw Error();}});denied.monitor({name:'Test'});assert.equal(denied.persistent,false);});
test('drawn AOIs validate geographical extent and reject crossing/empty outlines',()=>{assert.ok(validBounds([60,39,65,42]));assert.equal(validBounds([-190,39,65,42]),false);assert.ok(validateDrawnPolygon([[0,0],[2,0],[1,1],[2,2],[0,2]]));assert.throws(()=>validateDrawnPolygon([[0,0],[2,2],[0,2],[2,0]]));assert.throws(()=>validateDrawnPolygon([[0,0],[1,0],[2,0]]));});
test('replay exposes only available observations and no completed-day calendar value or nonexistent sensor',async()=>{const rows=[row('a'),row('b','08:00',65.02)],coverage=[{product:'MODIS_SP',start:'2024-08-01',end:'2024-08-31',processing:'SP'}],data=new Map([['summary',{days:supportDaily(supportRows(rows),coverage),coverage,eventSamples:[],periods:[]}],['raw',encodeRaw(rows)],['zones',{rows:[]}]]),metadata={builtAt:'2024-09-01T00:00:00Z',sources:[],cases:[{id:'x',name:'X',bounds:[64,40,66,42],summary:{file:'summary'},partitions:[{year:2024,bounds:[64,40,66,42],raw:{file:'raw'},zones:{file:'zones'},coverage}]}]},engine=createMonitorEngine({metadata,loadFiles:async entries=>entries.map(e=>data.get(e.file))});await engine.load({caseID:'x',mode:'history',month:'2024-08',seasonDays:7});const r=await engine.replay(Date.parse('2024-08-01T01:00:00Z'));assert.equal(r.rawDetections,1);assert.equal(r.daily.length,1);assert.equal(r.daily[0].s,null);assert.equal(r.calendarDays.at(-1).cells,r.daily[0].cells);assert.ok(r.events.every(e=>e.latestTime<=r.clock));assert.equal(engine.detail(r.events[0].id).raw.length,1);});

test('untrained VIIRS scaling is explicit rather than a false normal state',()=>{const days=Array.from({length:8},(_,i)=>day((2014+i)+'-08-01',0));const c=seasonalBaseline(days,{...day('2022-08-01',0),s:40});assert.equal(c.available,false);assert.equal(c.calibrationAvailable,false);assert.equal(monitoringState(c).state,'Insufficient history');});

test('persisted identity is recovered when only later overlapping source IDs remain in the registry',()=>{const original=[row('older','00:00',65,'2024-07-31'),row('first'),row('second','04:00'),row('last','08:00')],old=trackEvents(original)[0],compact={...old,sourceIDs:[old.sourceIDs.at(-1)],frames:[]};assert.equal(trackEvents(original.slice(1),[compact])[0].id,old.id);});

test('an empty update retains recent registry activity rather than implying extinguishment',()=>{const old=trackEvents([row('known')]);const retained=trackEvents([],old,{now:Date.parse('2024-08-02T00:00:00Z')});assert.equal(retained[0].id,old[0].id);assert.ok(retained[0].retained);assert.equal(trackEvents([],old,{now:Date.parse('2024-08-12T00:00:00Z')}).length,0);});

test('missing historical metadata preserves the chosen live AOI and exposes unavailable context',async()=>{const today=new Date().toISOString().slice(0,10),engine=createMonitorEngine({metadata:null,loadLive:async()=>({retrievedAt:new Date().toISOString(),dateStart:today,dateEnd:today,requests:[{product:'MODIS_NRT'}],data:[{...row('inside','00:00',-121,today),lat:39,product:'MODIS_NRT'},{...row('outside','00:00',65,today),product:'MODIS_NRT'}]})});const r=await engine.load({caseID:'california',mode:'live',seasonDays:7});assert.equal(r.rawDetections,1);assert.equal(r.context.available,false);assert.equal(r.historicalUnavailable,true);await assert.rejects(engine.load({caseID:'california',mode:'history',month:'2024-09'}),/coverage is unavailable/);});

test('lazy raw partition filtering preserves original records while applying month and AOI before expansion',()=>{const rows=[row('a'),row('other','00:00',66),row('old','00:00',65,'2023-08-01')],selected=decodeSelectedRecords(encodeRaw(rows),r=>r.lon<65.5,'2024-08');assert.equal(selected.length,1);assert.equal(selected[0].id,'a');assert.equal(selected[0].scan,1);});


test('successive live loads retain complete in-memory identities when local registry is absent',async()=>{const today=new Date().toISOString().slice(0,10),records=[row('earliest','00:00',65,today),row('overlap','04:00',65,today)],engine=createMonitorEngine({metadata:null,loadLive:async()=>({retrievedAt:new Date().toISOString(),dateStart:today,dateEnd:today,requests:[{product:'MODIS_NRT'}],data:records.map(r=>({...r,product:'MODIS_NRT'}))})});const first=await engine.load({caseID:'world',mode:'live'});const id=first.events[0].id;records.shift();const second=await engine.load({caseID:'world',mode:'live',registry:[]});assert.equal(second.events[0].id,id);await engine.replay(Date.parse(today+'T00:01:00Z'));const third=await engine.load({caseID:'world',mode:'live',registry:[]});assert.equal(third.events[0].id,id);});

test('queue and detail expose source pixel coordinates and replay never uses later locations',async()=>{
 const date='2024-08-01',records=[{...row('earliest','00:00',65.12345,date),lat:41.23456},{...row('later','08:00',65.12456,date),lat:41.23456}],engine=createMonitorEngine({metadata:null,loadLive:async()=>({retrievedAt:new Date().toISOString(),dateStart:date,dateEnd:date,requests:[{product:'MODIS_NRT'}],data:records})});
 await engine.load({caseID:'world',mode:'live'});const replay=await engine.replay(Date.parse(date+'T01:00:00Z'));assert.equal(replay.events.length,1);assert.equal(replay.events[0].location.lon,65.12345);assert.equal(replay.events[0].location.lat,41.23456);assert.deepEqual(engine.detail(replay.events[0].id).location,replay.events[0].location);
 const later=await engine.replay(Date.parse(date+'T09:00:00Z'));assert.equal(later.events[0].location.lon,65.12456);assert.ok(engine.detail(later.events[0].id).raw.some(r=>r.lon===later.events[0].location.lon));
});

test('worldwide queue sampling never truncates global totals or the map evidence',async()=>{
 const date='2024-08-01',records=Array.from({length:256},(_,i)=>({...row('global-'+i,'00:00',-150+(i%16)*18,date),lat:-60+Math.floor(i/16)*8})),engine=createMonitorEngine({metadata:null,loadLive:async()=>({retrievedAt:new Date().toISOString(),dateStart:date,dateEnd:date,requests:[{product:'MODIS_NRT'}],data:records})});
 const result=await engine.load({caseID:'world',mode:'live'});assert.equal(result.queueMode,'worldwide-evidence');assert.equal(result.totalEvents,256);assert.equal(result.rawDetections,256);assert.equal(result.events.length,250);assert.ok(new Set(engine.geometry({view:'MODIS'}).map(p=>p.eventID)).size===256);assert.ok(result.events.every(e=>e.location));
});
