import {qualityRows,trackEvents,supportBounds,eventTrend,sourceID} from './event-tracking.js';
import {decodeRecords,decodeSelectedRecords,supportRows,supportDaily,monitoringZone,monitorCases} from './monitor-preprocess.js';
import {seasonalBaseline,primeSeasonalModel,assessEvent,priorityQueue,criticalPeriods,distribution,monitoringState,quantile} from './early-warning.js';
import {compileGeometry} from './boundary-geometry.js';
const intersects=(a,b)=>a[0]<=b[2]&&a[2]>=b[0]&&a[1]<=b[3]&&a[3]>=b[1];
const inBounds=(r,b)=>!b||r.lon>=b[0]&&r.lon<=b[2]&&r.lat>=b[1]&&r.lat<=b[3];
export function createMonitorEngine({loadFiles,loadLive,metadata,loadBoundary=async()=>null}){
 let rows=[],current=[],events=[],summary=null,area=null,args=null,clock=Date.now(),snapshot=null,days=[],baselineCache=new Map(),presetSummary=null;const zeroCoverage=new Map(),zoneTiles=new Map(),calendarCache=new Map(),periodCache=new Map(),customCache=new Map();let polygonTest=null,countryTest=null,customZones=null,liveScope=null,liveRegistry=[];
 const inside=r=>inBounds(r,args?.bounds)&&(!polygonTest||polygonTest(r))&&(!countryTest||countryTest(r));
 async function zoneHistory(zone,archive=area){if(customZones)return customZones.get(zone.id)||supportDaily([],presetSummary.coverage);const key=archive.id+':'+zone.id;if(baselineCache.has(key))return baselineCache.get(key);const prepared=archive.zoneArchives?.find(p=>p.bounds[0]<zone.bounds[2]&&p.bounds[2]>zone.bounds[0]&&p.bounds[1]<zone.bounds[3]&&p.bounds[3]>zone.bounds[1]);if(prepared){if(!zoneTiles.has(prepared.entry.file))zoneTiles.set(prepared.entry.file,(await loadFiles([prepared.entry]))[0]);const tile=zoneTiles.get(prepared.entry.file),record=tile.zones[zone.id],positive=new Map((record?.rows||[]).map(r=>[r[0],r])),out=(zeroCoverage.has(archive.id)?zeroCoverage.get(archive.id):(zeroCoverage.set(archive.id,supportDaily([],tile.coverage)),zeroCoverage.get(archive.id))).map(d=>{const r=positive.get(d.date);return r?{...d,m:r[1],s:r[2],j:r[3],n:r[4],cells:r[5],frpMax:r[6],shared:r[7]}:d;});primeSeasonalModel(out,record?.model);baselineCache.set(key,out);return out;}const partitions=archive.partitions.filter(p=>p.bounds[0]<zone.bounds[2]&&p.bounds[2]>zone.bounds[0]&&p.bounds[1]<zone.bounds[3]&&p.bounds[3]>zone.bounds[1]);let out=[];for(const p of partitions){const z=(await loadFiles([p.zones]))[0],map=new Map(z.rows.filter(r=>r[0]===zone.id).map(r=>[r[1],{date:r[1],m:r[2],s:r[3],j:r[4],n:r[5],cells:r[6],frpMax:r[7],shared:r[8],processing:'SP'}]));const zeros=supportDaily([],p.coverage);out.push(...zeros.map(d=>map.has(d.date)?{...map.get(d.date),processing:d.processing}:d));}baselineCache.set(key,out);while(baselineCache.size>1500)baselineCache.delete(baselineCache.keys().next().value);return out;}
 async function customHistory(){const key=JSON.stringify([area.id,args.bounds,args.polygon]);if(customCache.has(key))return customCache.get(key);const parts=area.partitions.filter(p=>!args.bounds||intersects(p.bounds,args.bounds)),raw=(await loadFiles(parts.map(p=>p.raw))).flatMap(value=>decodeSelectedRecords(value,inside)),cells=supportRows(raw),zones=new Map();for(const c of cells){const id=monitoringZone(c.lat,c.lon).id;if(!zones.has(id))zones.set(id,[]);zones.get(id).push(c);}const value={days:supportDaily(cells,presetSummary.coverage),zones:new Map([...zones].map(([id,cells])=>[id,supportDaily(cells,presetSummary.coverage)]))};customCache.set(key,value);while(customCache.size>3)customCache.delete(customCache.keys().next().value);return value;}
 async function load(input){
  args={...input};area=metadata?.cases.find(c=>c.id===args.caseID)||monitorCases[args.caseID]||null;polygonTest=args.polygon?compileGeometry(args.polygon):null;const country=area?.id==='uzbekistan'?await loadBoundary(area.id):null;countryTest=country?compileGeometry(country):null;customZones=null;presetSummary=area?.summary?(await loadFiles([area.summary]))[0]:null;days=presetSummary?.days||[];
  if(area?.partitions&&(args.bounds||args.polygon)){const custom=await customHistory();days=custom.days;customZones=custom.zones;}
  if(args.mode==='history'){if(!area?.partitions)throw Error('Historical coverage is unavailable for this area');if(!/^\d{4}-(0[1-9]|1[0-2])$/.test(args.month))throw Error('Choose a valid historical month');const year=+args.month.slice(0,4),parts=area.partitions.filter(p=>p.year===year&&(!args.bounds||intersects(p.bounds,args.bounds)));rows=(await loadFiles(parts.map(p=>p.raw))).flatMap(value=>decodeSelectedRecords(value,inside,args.month));snapshot={retrievedAt:metadata.builtAt,dateStart:args.month+'-01',dateEnd:args.month+'-'+new Date(Date.UTC(year,+args.month.slice(5),0)).getUTCDate(),source:'NASA FIRMS historical archives',requests:presetSummary.coverage.filter(c=>c.start<=args.month+'-31'&&c.end>=args.month+'-01'),processing:rows.some(r=>r.product.endsWith('NRT'))?'Provisional NRT':'Standard Processing'};clock=Date.parse(snapshot.dateEnd+'T23:59:59Z');}
  else{const live=await loadLive();snapshot=live;rows=live.data.filter(r=>area?inBounds(r,area.bounds)&&inside(r):inside(r));clock=Date.now();}
  const scope=JSON.stringify([args.caseID,args.bounds,args.polygon]);const registry=args.mode==='live'&&liveScope===scope?liveRegistry:(args.registry||[]);const result=await refresh(registry);if(args.mode==='live'){liveScope=scope;liveRegistry=compactRegistry();}return result;
 }
 async function refresh(registry=[]){
  if(args.debug)console.time('events');current=qualityRows(rows.filter(r=>Date.parse(r.date+'T'+r.time+':00Z')<=clock));events=trackEvents(current,registry,{now:clock});if(args.debug){console.timeEnd('events');console.log({raw:current.length,events:events.length});console.time('context');}
  const coverage=(snapshot.requests||[]).map(r=>({product:r.product,start:r.start&&r.start>snapshot.dateStart?r.start:snapshot.dateStart,end:[r.end||snapshot.dateEnd,snapshot.dateEnd,new Date(clock).toISOString().slice(0,10)].sort()[0],processing:args.mode==='history'&&!r.product.endsWith('NRT')?'SP':'NRT'})).filter(c=>c.start<=c.end),cells=supportRows(current),daily=supportDaily(cells,coverage);
  let currentDay=daily.at(-1),context=area&&currentDay?seasonalBaseline(days,currentDay,{seasonDays:args.seasonDays??7,minYears:args.minYears??5}):{available:false,n:0,percentile:null,median:null};
  const assessed=[],samples=presetSummary?.eventSamples||[],sampleMonths=new Map(),year=new Date(clock).getUTCFullYear();for(const sample of samples)if(sample.processing==='SP'&&+sample.date.slice(0,4)<year&&inBounds({lat:sample.center[0],lon:sample.center[1]},args.bounds||area?.bounds)){const month=sample.date.slice(5,7);if(!sampleMonths.has(month))sampleMonths.set(month,{growth:[],persistence:[]});const bucket=sampleMonths.get(month);if(Number.isFinite(sample.growth))bucket.growth.push(sample.growth);if(Number.isFinite(sample.duration))bucket.persistence.push(sample.duration);}
  // Current event context uses fixed 0.25-degree monitoring zones: current and historical totals share exactly that support selection.
  const zoneCurrent=new Map(),zoneRaw=new Map(),bySource=new Map(current.map(r=>[sourceID(r),r])),previousCache=new Map(),contexts=new Map();for(const c of cells){const z=monitoringZone(c.lat,c.lon).id;if(!zoneCurrent.has(z))zoneCurrent.set(z,[]);zoneCurrent.get(z).push(c);}
  for(const [id,records] of zoneCurrent){const ids=new Set(records.flatMap(c=>c.sourceObservationIDs));zoneRaw.set(id,[...ids].map(id=>bySource.get(id)).filter(Boolean));}
  for(const e of events){const first=e.frames[0]?.cells[0],zone=monitoringZone(first?.lat??e.center[0],first?.lon??e.center[1]);let local={available:false,n:0,percentile:null,scope:'No comparable archived monitoring zone'};
   const archive=(area?.partitions?area:null)||(!args.bounds&&!args.polygon?metadata?.cases.find(c=>inBounds({lat:(zone.bounds[1]+zone.bounds[3])/2,lon:(zone.bounds[0]+zone.bounds[2])/2},c.bounds)):null);let history=null;
   if(archive&&intersects(zone.bounds,archive.bounds)){history=await zoneHistory(zone,archive);const liveDays=supportDaily(zoneCurrent.get(zone.id)||[],coverage),date=new Date(e.latestTime).toISOString().slice(0,10),d=liveDays.find(d=>d.date===date);if(d){const key=archive.id+':'+zone.id+':'+date;if(!contexts.has(key))contexts.set(key,{...seasonalBaseline(history,d,{asOf:new Date(clock).toISOString().slice(0,10),seasonDays:args.seasonDays??7,minYears:args.minYears??5}),scope:'0.25° monitoring zone within '+archive.name+(customZones?' and selected Area of Interest':''),bounds:zone.bounds});local=contexts.get(key);}}
   const prior=sampleMonths.get(new Date(e.latestTime).toISOString().slice(5,7))||{growth:[],persistence:[]};
   const preliminary=assessEvent(e,local,{now:clock,growthDistribution:prior.growth,persistenceDistribution:prior.persistence});const previousFrame=e.frames.at(-2);let previousP=null;
   if(previousFrame&&history&&local.available&&local.percentile>=95&&preliminary.trend.state==='Rapidly increasing'&&!preliminary.stale){const key=zone.id+':'+previousFrame.end+':'+new Date(e.latestTime).toISOString().slice(0,10);if(!previousCache.has(key)){const previousCells=supportRows((zoneRaw.get(zone.id)||[]).filter(r=>Date.parse(r.date+'T'+r.time+':00Z')<=previousFrame.end)).filter(c=>monitoringZone(c.lat,c.lon).id===zone.id),previousDay=supportDaily(previousCells,coverage).find(d=>d.date===new Date(previousFrame.end).toISOString().slice(0,10));previousCache.set(key,previousDay?seasonalBaseline(history,previousDay,{asOf:new Date(previousFrame.end).toISOString().slice(0,10),seasonDays:args.seasonDays??7,minYears:args.minYears??5}).percentile:null);}previousP=previousCache.get(key);}
   const assessedEvent=previousP===null?preliminary:assessEvent(e,local,{now:clock,growthDistribution:prior.growth,persistenceDistribution:prior.persistence,previousPercentile:previousP});assessed.push(assessedEvent);
  }
  if(args.debug){console.timeEnd('context');console.time('calendar');}const queue=priorityQueue(assessed);events=assessed;
  const compact=e=>{const {frames,cellIDs,sourceIDs,...rest}=e,{model,references,footprint,...context}=e.context;return {...rest,context,frameCount:frames.length};};
  const periodKey=JSON.stringify([area?.id,args.bounds,args.polygon,args.seasonDays]);let periods=[];if(area?.partitions){if(customZones||args.seasonDays!==7){if(!periodCache.has(periodKey))periodCache.set(periodKey,criticalPeriods(days,{options:{seasonDays:args.seasonDays??7}}));periods=periodCache.get(periodKey);}else periods=presetSummary.periods||[];}periods=periods.filter(p=>Date.parse(p.end+'T23:59:00Z')<=clock);
  const calendarKey=JSON.stringify([area?.id,args.bounds,args.polygon,args.seasonDays]);let historicalCalendar=calendarCache.get(calendarKey);if(!historicalCalendar){historicalCalendar=(!customZones?presetSummary?.calendars?.[args.seasonDays??7]:null)||days.map(d=>{const c=seasonalBaseline(days,d,{seasonDays:args.seasonDays??7});return {...d,value:c.value,percentile:c.available?c.percentile:null,reference:c.reference};});calendarCache.set(calendarKey,historicalCalendar);while(calendarCache.size>4)calendarCache.delete(calendarCache.keys().next().value);}const calendarMap=new Map(historicalCalendar.filter(d=>args.mode!=='history'||d.date<new Date(clock).toISOString().slice(0,10)).map(d=>[d.date,d]));for(const d of daily)if(args.mode==='history'&&d.date===new Date(clock).toISOString().slice(0,10)||args.mode==='live'&&(!calendarMap.has(d.date)||calendarMap.get(d.date).processing==='NRT')){const c=seasonalBaseline(days,d,{seasonDays:args.seasonDays??7});calendarMap.set(d.date,{...d,value:c.value,percentile:c.available?c.percentile:null});}const calendarDays=[...calendarMap.values()].sort((a,b)=>a.date.localeCompare(b.date)),seasonality=Array.from({length:12},(_,i)=>quantile(calendarDays.filter(d=>d.processing==='SP'&&+d.date.slice(5,7)===i+1).map(d=>d.value).filter(Number.isFinite),.5));
  summary={area:area?{id:area.id,name:area.name,bounds:area.bounds,description:area.description}:null,mode:args.mode,snapshot:{...snapshot,data:undefined},context,events:queue.slice(0,250).map(compact),totalEvents:queue.length,rawDetections:current.length,supportCells:cells.length,daily,calendarDays,seasonality,periods:periods||[],clock,frameTimes:[...new Set(current.map(r=>Math.floor(Date.parse(r.date+'T'+r.time+':00Z')/900000)*900000))].sort((a,b)=>a-b),warning:'Activity groups are satellite evidence, not confirmed wildfires. Absence of new detections does not establish extinguishment.',historicalUnavailable:!presetSummary,offline:!!metadata?.offline};
  if(args.debug)console.timeEnd('calendar');return summary;
 }
 async function replay(time){clock=time;return await refresh([]);}
 function detail(id){const e=events.find(e=>e.id===id||e.aliases.includes(id));if(!e)throw Error('Event is not present at this observation time');const ids=new Set(e.sourceIDs);return {...e,frames:e.frames.map(({cells,...f})=>({...f,cells:cells.length,footprintKm2Approx:cells.length})),raw:current.filter(r=>ids.has(sourceID(r))),harmonizationVersion:'evidence-grid-v2',sourceCatalog:metadata?.sources.filter(s=>e.products.includes(s.product)&&s.start<=new Date(e.latestTime).toISOString().slice(0,10)&&s.end>=new Date(e.firstTime).toISOString().slice(0,10))||[],baselineInterpretation:'Zone-wide seasonal context is shown separately from the individual activity group. The zone may contain several activities. Latest UTC day may be incomplete.'};}
 function geometry({id=null,time=clock,view='Harmonized',bounds,footprintMode='latest'}){const selected=id?events.filter(e=>e.id===id||e.aliases.includes(id)):events;const out=[];for(const e of selected)for(const frame of (footprintMode==='all'?e.frames:e.frames.slice(-1)))if(frame.time<=time){if(view==='Harmonized')for(const c of frame.cells){if(bounds&&!inBounds(c,bounds))continue;out.push({bounds:supportBounds(c),eventID:e.id,time:frame.time,sensors:c.sensors,weight:c.evidenceWeight,state:e.state,view});}}
  if(view!=='Harmonized'){const sourceEvents=new Map(selected.flatMap(e=>(footprintMode==='all'?e.sourceIDs:[...new Set(e.frames.at(-1)?.cells.flatMap(c=>c.sourceObservationIDs)||[])]).map(id=>[id,e.id]))),ids=new Set(sourceEvents.keys());for(const r of current)if(ids.has(sourceID(r))&&Date.parse(r.date+'T'+r.time+':00Z')<=time&&(view==='Compare'||view===r.sensor)&&inBounds(r,bounds)){const lat=r.lat,lon=r.lon,width=(r.scan||(r.sensor==='MODIS'?1:.375))/(2*111.32*Math.cos(lat*Math.PI/180)),height=(r.track||(r.sensor==='MODIS'?1:.375))/(2*111.32);out.push({bounds:[lon-width,lat-height,lon+width,lat+height],eventID:sourceEvents.get(sourceID(r)),time:Date.parse(r.date+'T'+r.time+':00Z'),sensors:[r.sensor],view:r.sensor,sourceIDs:[sourceID(r)]});}}
  return out;
 }
 function compactRegistry(){return events.map(({id,firstTime,latestTime,sourceIDs,center,bounds,sensors,satellites,products,aliases,rawDetections,harmonizedCells,acquisitionGroups,durationHours,nearTimeCells,frpMax,uncertainty,frames})=>({id,firstTime,latestTime,sourceIDs,center,bounds,sensors,satellites,products,aliases,rawDetections,harmonizedCells,acquisitionGroups,durationHours,nearTimeCells,frpMax,uncertainty,frames:[]}));}
 return {load,replay,detail,geometry,get registry(){return compactRegistry();}};
}
