import {mapOptions,tileOptions,minimumWorldZoom} from './map-policy.js';import {basemaps,imageryDate} from './basemaps.js';import {validateDrawnPolygon} from './monitor-aoi.js';import {focusBounds,geometryPolygons,ringBounds} from './boundary-geometry.js';
export function createMonitorMap({ask,onInspect,onArea,onNotice}){
 const $=id=>document.getElementById(id),map=L.map('monitor-map',{...mapOptions,zoomAnimation:window.atlasMotion.enabled,fadeAnimation:window.atlasMotion.enabled}).setView([41,65],5);map.zoomControl.setPosition('bottomright');
 const canvas=document.createElement('canvas');canvas.className='monitor-leaflet-canvas leaflet-zoom-hide';map.getPane('overlayPane').append(canvas);let footprintMode='latest',layers=[],visible=true,selected=null,view='Harmonized',drawTicket=0,busy=false,queued=false,positions=[],draft=null,areaOutline=null,mode=null,corners=[],restoreZoom=false,baseTicket=0;
 const pane=map.createPane('monitorAreas');pane.style.zIndex='420';
 function viewport(){const b=map.getBounds();return [b.getWest(),b.getSouth(),b.getEast(),b.getNorth()];}
 async function draw(){queued=true;drawTicket++;if(busy)return;busy=true;try{while(queued){queued=false;const ticket=drawTicket;if(!visible){canvas.style.visibility='hidden';positions=[];$('monitor-map-note').textContent='Data overlays hidden. Map navigation remains available; Show overlays restores the selected evidence view.';continue;}const records=await ask('geometry',{id:null,view,bounds:viewport(),footprintMode});if(ticket!==drawTicket)continue;const size=map.getSize(),ratio=Math.min(devicePixelRatio,1.5),position=map.containerPointToLayerPoint([0,0]);L.DomUtil.setPosition(canvas,position);canvas.width=Math.round(size.x*ratio);canvas.height=Math.round(size.y*ratio);canvas.style.width=size.x+'px';canvas.style.height=size.y+'px';const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);canvas.style.visibility='';positions=[];const colors={Critical:'#ff788d',Elevated:'#ffa86b',Watch:'#efcf87',Normal:'#a5e6bc','Insufficient history':'#80c5fa',MODIS:'#ff965c',VIIRS:'#77bfff'},pixels=new Map();
   for(const r of records){const a=map.latLngToContainerPoint([r.bounds[3],r.bounds[0]]),b=map.latLngToContainerPoint([r.bounds[1],r.bounds[2]]);if(b.x<0||a.x>size.x||b.y<0||a.y>size.y)continue;const x=a.x,y=a.y,w=Math.max(1,b.x-a.x),h=Math.max(1,b.y-a.y);const key=map.getZoom()<8?Math.floor(x)+':'+Math.floor(y)+':'+(r.view==='Harmonized'?r.state:r.view):null;if(key&&pixels.has(key))continue;if(key)pixels.set(key,true);positions.push({x,y,w,h,id:r.eventID});ctx.fillStyle=colors[r.view==='Harmonized'?r.state:r.view]||'#8ac9ff';ctx.globalAlpha=selected===r.eventID?.8:.4;ctx.fillRect(x,y,w,h);if(selected===r.eventID&&w>4){ctx.globalAlpha=.9;ctx.strokeStyle='#effaff';ctx.strokeRect(x,y,w,h);}}
   $('monitor-map-note').textContent=records.length.toLocaleString()+' observed '+(view==='Harmonized'?'footprint-support cells':'raw approximate satellite pixels')+' in this view · '+(footprintMode==='latest'?'latest acquisition per activity':'all observed support through the selected time')+'. Subpixel support overlaps share a display pixel. Not burned area or interpolated fire perimeter.';
  }}catch(error){onNotice('Map geometry unavailable: '+error.message);}finally{busy=false;}}
 map.on('moveend',draw);map.on('zoomstart',()=>canvas.style.visibility='hidden');map.on('click',e=>{if(mode){corners.push([e.latlng.lng,e.latlng.lat]);paintDraft();if(mode==='rectangle'&&corners.length===2)finishDrawing();return;}if(!visible)return;const p=e.containerPoint;let best=positions.find(r=>p.x>=r.x-3&&p.x<=r.x+r.w+3&&p.y>=r.y-3&&p.y<=r.y+r.h+3);if(best?.id)onInspect(best.id);});
 async function setBase(name){const id=++baseTicket;for(const layer of layers)map.removeLayer(layer);layers=[];const config=basemaps[name]||basemaps.satellite,date=imageryDate(new Date().toISOString().slice(0,10));const raster=config.vector?basemaps.satellite:config;layers.push(L.tileLayer(raster.url.replace('{date}',date),{...tileOptions,maxNativeZoom:raster.maxNativeZoom,attribution:raster.attribution}).addTo(map));if(config.vector)try{const {createVectorBasemap}=await import('./vector-basemap.js');const layer=await createVectorBasemap(name);if(id!==baseTicket)return;layer.addTo(map);for(const old of layers)map.removeLayer(old);layers=[layer];map.attributionControl.addAttribution(config.attribution);}catch{onNotice('Street renderer unavailable; satellite imagery retained.');}}
 $('monitor-basemap').onchange=()=>setBase($('monitor-basemap').value);setBase('satellite');$('monitor-footprints').onchange=()=>{footprintMode=$('monitor-footprints').value;draw();};$('monitor-view').onchange=()=>{view=$('monitor-view').value;draw();};$('monitor-hide').onclick=()=>{visible=!visible;$('monitor-hide').textContent=visible?'Hide overlays':'Show overlays';$('monitor-hide').setAttribute('aria-pressed',String(!visible));draw();};
 function fit(bounds){map.fitBounds([[Math.max(-85,bounds[1]),bounds[0]],[Math.min(85,bounds[3]),bounds[2]]],{padding:[40,55],maxZoom:13,animate:window.atlasMotion.enabled});}
 function clearDraft(){if(draft)map.removeLayer(draft);draft=null;}
 function paintDraft(){clearDraft();if(mode==='rectangle'&&corners.length===1)draft=L.circleMarker([corners[0][1],corners[0][0]],{radius:4,color:'#9dd3ff'}).addTo(map);else if(corners.length>1)draft=L.polyline(corners.map(([x,y])=>[y,x]),{color:'#8bcaff',weight:2,dashArray:'5 5'}).addTo(map);$('monitor-draw-polygon').textContent=mode==='polygon'?'Finish polygon ('+corners.length+' points)':'Draw polygon';}
 function stopDrawing(){mode=null;corners=[];clearDraft();if(restoreZoom)map.doubleClickZoom.enable();$('monitor-draw-rectangle').textContent='Draw rectangle';$('monitor-draw-polygon').textContent='Draw polygon';}
 function startDrawing(kind){if(mode===kind){if(kind==='polygon'&&corners.length>=3)finishDrawing();else stopDrawing();return;}stopDrawing();mode=kind;restoreZoom=map.doubleClickZoom.enabled();map.doubleClickZoom.disable();$('monitor-draw-rectangle').textContent=kind==='rectangle'?'Cancel rectangle':'Draw rectangle';onNotice(kind==='rectangle'?'Choose two opposite corners on the map. Escape cancels.':'Click polygon vertices, then Finish polygon. Escape cancels.');}
 function finishDrawing(){const kind=mode,points=corners.slice();if(kind==='polygon'&&points.length<3){onNotice('A polygon needs at least three vertices.');return;}let geometry;if(kind==='rectangle'){const [a,b]=points,w=Math.min(a[0],b[0]),s=Math.min(a[1],b[1]),e=Math.max(a[0],b[0]),n=Math.max(a[1],b[1]);if(e-w<1e-7||n-s<1e-7){onNotice('Choose an area with width and height.');stopDrawing();return;}geometry={type:'Polygon',coordinates:[[[w,s],[e,s],[e,n],[w,n],[w,s]]]};}else{try{validateDrawnPolygon(points);}catch(error){onNotice(error.message);return;}geometry={type:'Polygon',coordinates:[[...points,points[0]]]};}stopDrawing();setArea(geometry,'Custom Area of Interest');onArea({bounds:focusBounds(geometry),polygon:geometry,name:'Custom Area of Interest'});}
 function setArea(geometry,name){if(areaOutline)map.removeLayer(areaOutline);areaOutline=geometry?L.geoJSON({type:'Feature',geometry},{pane:'monitorAreas',style:{color:'#91cfff',weight:2,fillOpacity:.05}}).addTo(map):null;$('monitor-map-selection').hidden=!geometry;$('monitor-area-name').textContent=name||'Custom Area of Interest';$('monitor-clear-area').hidden=!geometry;}
 $('monitor-draw-rectangle').onclick=()=>startDrawing('rectangle');$('monitor-draw-polygon').onclick=()=>startDrawing('polygon');$('monitor-map-clear').onclick=()=>{stopDrawing();setArea(null);onArea(null);};$('monitor-clear-area').onclick=()=>$('monitor-map-clear').click();document.addEventListener('keydown',e=>{if(e.key==='Escape'&&mode){e.preventDefault();stopDrawing();}});
 const panel=document.querySelector('.monitor-map-panel'),anchor=document.createComment('Map home'),main=document.querySelector('main'),navigation=document.querySelector('.site-nav');panel.before(anchor);const inspectLink=document.createElement('button');inspectLink.className='monitor-map-inspect';inspectLink.textContent='View selected activity details ↗';inspectLink.hidden=true;document.querySelector('.monitor-map-frame').append(inspectLink);inspectLink.onclick=()=>{if(large)$('monitor-map-enlarge').click();$('monitor-event-detail').scrollIntoView({behavior:'instant',block:'start'});};let large=false,originalFocus=null;$('monitor-map-enlarge').onclick=()=>{large=!large;panel.classList.toggle('map-large',large);document.body.classList.toggle('monitor-map-open',large);document.documentElement.classList.toggle('monitor-map-open',large);$('monitor-map-enlarge').textContent=large?'× Close large map':'↗ Enlarge map';$('monitor-map-enlarge').setAttribute('aria-expanded',String(large));if(large){originalFocus=document.activeElement;document.body.append(panel);main.inert=true;navigation.inert=true;panel.setAttribute('role','dialog');panel.setAttribute('aria-modal','true');$('monitor-map-enlarge').focus();}else{anchor.after(panel);main.inert=false;navigation.inert=false;panel.removeAttribute('role');panel.removeAttribute('aria-modal');originalFocus?.focus();}requestAnimationFrame(()=>{map.invalidateSize({pan:true,animate:false});draw();});};document.addEventListener('keydown',e=>{if(e.key==='Escape'&&large&&!mode&&!e.defaultPrevented)$('monitor-map-enlarge').click();if(e.key==='Tab'&&large){const nodes=[...panel.querySelectorAll('button,select,input,a[href]')].filter(n=>n.offsetParent!==null),first=nodes[0],last=nodes.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});new ResizeObserver(()=>{map.invalidateSize({pan:true,animate:false});map.setMinZoom(minimumWorldZoom(map.getSize()));draw();}).observe($('monitor-map'));
 (async()=>{try{const r=await fetch('./assets/boundaries/world.json'),world=await r.json();L.geoJSON(world,{interactive:false,style:{color:'#8fc7e7',weight:.65,fillOpacity:0}}).addTo(map);$('monitor-country-names').replaceChildren(...world.features.map(f=>{const o=document.createElement('option');o.value=f.properties.name;return o;}));$('monitor-location-search').onsubmit=e=>{e.preventDefault();const name=$('monitor-location').value.toLowerCase(),country=world.features.find(f=>f.properties.name.toLowerCase()===name);if(!country){onNotice('Choose a country from the English search suggestions.');return;}const b=focusBounds(country.geometry),boxes=geometryPolygons(country.geometry).map(r=>ringBounds(r[0])),allBounds=[Math.min(...boxes.map(b=>b[0])),Math.min(...boxes.map(b=>b[1])),Math.max(...boxes.map(b=>b[2])),Math.max(...boxes.map(b=>b[3]))];fit(b);setArea(country.geometry,country.properties.name);onArea({bounds:allBounds,polygon:country.geometry,name:country.properties.name,caseID:country.properties.country==='UZB'?'uzbekistan':'world'});};}catch{onNotice('Country search unavailable; map drawing still works.');}})();
 return {draw,fit,setArea,select(id){selected=id;inspectLink.hidden=!id;draw();},cancelDrawing:stopDrawing};
}
