import {readFile,writeFile,mkdir} from 'node:fs/promises';import {gunzipSync,gzipSync} from 'node:zlib';import {createHash} from 'node:crypto';import assert from 'node:assert/strict';
import {createMonitorEngine} from './monitor-engine.js';import {seasonalBaseline,criticalPeriods,monitoringState} from './early-warning.js';
const root='data/monitor/',metadata=JSON.parse(await readFile(root+'manifest.json','utf8')),cache=new Map();
const loadFiles=async entries=>Promise.all(entries.map(async e=>{if(!cache.has(e.file))cache.set(e.file,JSON.parse(gunzipSync(await readFile(root+e.gzip))));return cache.get(e.file);}));
const boundary=JSON.parse(await readFile('assets/boundaries/countries/UZB.json','utf8')).country.geometry;
// Recalculate only derived period summaries after policy changes; no raw NASA source is changed.
for(const area of metadata.cases){const summary=(await loadFiles([area.summary]))[0];summary.periods=criticalPeriods(summary.days);const json=JSON.stringify(summary),gzip=gzipSync(json,{level:9});await writeFile(root+area.summary.gzip,gzip);area.summary.version=createHash('sha256').update(gzip).digest('hex').slice(0,12);area.summary.bytes=gzip.length;}
await writeFile(root+'manifest.json',JSON.stringify(metadata));
const periods=[['uzbekistan','2021-04','high seasonal activity'],['uzbekistan','2024-01','quiet winter'],['california','2023-09','later September comparison'],['california','2020-09','high activity with insufficient earlier years'],['amazon','2024-08','high dry-season activity'],['amazon','2023-08','contrasting dry-season activity'],['australia','2023-12','high southern-summer activity'],['australia','2023-05','contrasting southern-autumn activity']];
const reports=[];
for(const [caseID,month,description] of periods){
 console.log('Sequential NASA replay: '+caseID+' '+month);const area=metadata.cases.find(c=>c.id===caseID),archive=(await loadFiles([area.summary]))[0],engine=createMonitorEngine({metadata,loadFiles,loadBoundary:async()=>boundary});let started=performance.now(),full=await engine.load({caseID,mode:'history',month,seasonDays:7}),loadMs=Math.round(performance.now()-started);const times=full.frameTimes;
 // Sample acquisition boundaries across the period; include first/last, never interpolate observations.
 const checkpoints=[...new Set(Array.from({length:Math.min(12,times.length)},(_,i)=>times[Math.round(i*(times.length-1)/Math.max(1,Math.min(12,times.length)-1))]+899999))],history=[],stateByID=new Map(),triggers={},stability={transitions:0,comparisons:0},alerts=[],prefixTimings=[];let arithmetic=0;
 for(const time of checkpoints){started=performance.now();const r=await engine.replay(time);prefixTimings.push(Math.round(performance.now()-started));const warnings=r.events.filter(e=>['Watch','Elevated','Critical'].includes(e.state)&&!e.stale),states={};
  assert.ok(r.events.every(e=>e.latestTime<=time));assert.ok(r.calendarDays.every(d=>d.date<=new Date(time).toISOString().slice(0,10)));assert.ok(r.periods.every(p=>Date.parse(p.end+'T23:59:00Z')<=time));
  for(const e of r.events){states[e.state]=(states[e.state]||0)+1;if(stateByID.has(e.id)){stability.comparisons++;if(stateByID.get(e.id)!==e.state)stability.transitions++;}stateByID.set(e.id,e.state);if(['Watch','Elevated','Critical'].includes(e.state)&&!triggers[e.state])triggers[e.state]=new Date(time).toISOString();
   const d=engine.detail(e.id);assert.ok(d.raw.every(row=>Date.parse(row.date+'T'+row.time+':00Z')<=time));if(d.context.available){const values=d.context.references.map(x=>x.value),v=d.context.value,p=100*(values.filter(x=>x<v).length+.5*values.filter(x=>x===v).length)/values.length;assert.ok(Math.abs(p-d.context.percentile)<1e-9);assert.ok(d.context.references.every(x=>+x.year<new Date(time).getUTCFullYear()));assert.ok(Object.values(d.context.model.factors).every(f=>f.trainingYears.every(y=>+y<new Date(time).getUTCFullYear())));arithmetic++;}}
  alerts.push({time,ids:warnings.map(e=>e.id),percentiles:warnings.map(e=>e.context.percentile)});history.push({time:new Date(time).toISOString(),raw:r.rawDetections,support:r.supportCells,events:r.totalEvents,states,areaPercentile:r.context.available?r.context.percentile:null,areaYears:r.context.n});
 }
 let observedWarningHours=0,nonPersistent=0,exposures=0;for(let i=0;i<alerts.length-1;i++){const a=alerts[i],b=alerts[i+1],hours=(b.time-a.time)/3600000;for(const id of a.ids){exposures++;if(b.ids.includes(id))observedWarningHours+=hours;else nonPersistent++;}}
 const sensitivity={};for(const threshold of [75,80,90,95,99]){const eligible=archive.days.filter(d=>d.date.startsWith(month)).map(d=>seasonalBaseline(archive.days,d));sensitivity[threshold]={eligibleDays:eligible.filter(c=>c.available).length,daysAtOrAbove:eligible.filter(c=>c.available&&c.percentile>=threshold).length};}
 const zeroCases=archive.days.filter(d=>d.date.startsWith(month));assert.ok(zeroCases.length||!full.rawDetections);
 reports.push({caseID,month,description,acquisitionGroups:times.length,sampledPrefixes:history.length,loadMs,replayMedianMs:prefixTimings.sort((a,b)=>a-b)[Math.floor(prefixTimings.length/2)]??0,firstTriggers:triggers,statusComparisons:stability.comparisons,statusChanges:stability.transitions,statusChangeFraction:stability.comparisons?stability.transitions/stability.comparisons:null,sampledPersistentWarningHours:observedWarningHours,warningExposures:exposures,nonPersistentWarningProxyFraction:exposures?nonPersistent/exposures:null,percentileArithmeticChecks:arithmetic,thresholdSensitivity:sensitivity,history});
 cache.clear();
}
const result={builtAt:new Date().toISOString(),algorithm:metadata.algorithm,sourceFiles:metadata.sources.length,sourceCatalogSHA256:createHash('sha256').update(JSON.stringify(metadata.sources)).digest('hex'),policy:'monitoring-rules-v1',replay:'Chronological acquisition-prefix inference; earlier SP years only; no physical wildfire labels',scope:'12 stratified acquisition checkpoints per actual case month, first/last included. This is sampled replay, not exhaustive continuous alert validation.',reports};
await mkdir('validation',{recursive:true});await writeFile('validation/monitoring-replay.json',JSON.stringify(result,null,2));
const table=reports.map(r=>'| '+[r.caseID,r.month,r.sampledPrefixes,r.acquisitionGroups,Object.keys(r.firstTriggers).join('/')||'None',r.percentileArithmeticChecks,r.loadMs+' ms',r.replayMedianMs+' ms',r.statusChangeFraction===null?'—':(r.statusChangeFraction*100).toFixed(1)+'%',r.nonPersistentWarningProxyFraction===null?'—':(r.nonPersistentWarningProxyFraction*100).toFixed(1)+'%'].join(' | ')+' |').join('\n');
await writeFile('validation/MONITORING-REPLAY.md',`# Historical monitoring replay\n\nGenerated ${result.builtAt}. ${result.sourceFiles} actual source files. Work algorithm: ${result.algorithm}. Full measured results and source-catalog checksum: [monitoring-replay.json](monitoring-replay.json).\n\n| Area | Month | Prefixes | Available acquisition bins | Triggered states | Percentile checks | Initial load | Median prefix | State changes | Non-persistence proxy |\n|---|---|---:|---:|---|---:|---:|---:|---:|---:|\n${table}\n\nInference sees only detections at/before each checkpoint. Historical references and calibration training years must precede the checkpoint year. Calendar and period outputs are asserted not to reveal completed future days. Percentiles are checked against an independent midrank calculation from exported real reference-year values. Each run includes both first and last acquisition bins, with up to twelve stratified intermediate prefixes. Cases cover northern winter/spring, boreal September, Amazon August, southern autumn/summer, high and quieter activity, and insufficient-history states.\n\nFirst triggers are checkpoint timestamps, so detection timing is interval-censored by this sampling and satellite observation gaps. No ignition-to-alert delay or wildfire anomaly accuracy can be inferred. Anomaly arithmetic agreement is not independent hazard accuracy. JSON includes individual timestamps/counts, sampled hours of repeated warnings, state-transition fractions and threshold sensitivity (75/80/90/95/99) using actual earlier-year references.\n\n**False-warning frequency is not identifiable without independent wildfire/exposure ground truth.** The reported non-persistence proxy counts warning IDs that are not also warning IDs at the next sampled prefix, divided by sampled warning-ID exposures. It includes observation gaps, merges/splits, changed metrics and periods longer than 24 hours; it must not be presented as a wildfire false-positive rate. Alert persistence is observed between sampled acquisition boundaries, not continuous active burning.\n\nCritical requires at least twenty comparable prior years, extreme percentile, separated persistence and multi-sensor evidence. Prepared post-VIIRS archives usually lack twenty comparable paired years; an absence of Critical is a conservative coverage limit, not an implementation failure. The thresholds are transparent prototype policies, not emergency-dispatch guidance.\n`);
console.log(JSON.stringify({cases:reports.length,prefixes:reports.reduce((n,r)=>n+r.sampledPrefixes,0),arithmeticChecks:reports.reduce((n,r)=>n+r.percentileArithmeticChecks,0),report:'validation/MONITORING-REPLAY.md'}));
